import { QrCode } from 'lucide-react';
export interface NavItem {
  id: string;
  name: string;
  description: string;
  url: string;
  icon: string; // emoji 或 svg 路径
  tags: string[];
  stats?: {
    views?: number;
    likes?: number;
  };
  order?: number; // 排序权重（可选，默认按 views 排序）
}

export const TAG_COLORS: Record<string, string> = {
  "AI内容检测": "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300",
  "AI对话工具": "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-300",
  "AI写作工具": "bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-300",
  "AI视频工具": "bg-pink-100 text-pink-700 dark:bg-pink-900/30 dark:text-pink-300",
  "AI图像工具": "bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-300",
  "AI办公工具": "bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30 dark:text-cyan-300",
  "AI学习网站": "bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-300",
  "网盘搜索": "bg-indigo-100 text-indigo-700 dark:bg-indigo-900/30 dark:text-indigo-300",
  "开发工具": "bg-slate-100 text-slate-700 dark:bg-slate-900/30 dark:text-slate-300",
  "设计资源": "bg-rose-100 text-rose-700 dark:bg-rose-900/30 dark:text-rose-300",
  "在线工具": "bg-teal-100 text-teal-700 dark:bg-teal-900/30 dark:text-teal-300",
  "学习平台": "bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-300",
  "游戏平台": "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300",
  "社区论坛": "bg-violet-100 text-violet-700 dark:bg-violet-900/30 dark:text-violet-300",
};

export const getTagColor = (tag: string): string => {
  return TAG_COLORS[tag] || "bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300";
};

export const NAV_DATA: NavItem[] = [
  {
    id: "1",
    name: "ChatGPT",
    description: "OpenAI 开发的 AI 聊天助手，支持对话、写作、编程等多种任务",
    url: "https://chat.openai.com/",
    icon: "💬",
    tags: ["AI对话工具", "AI写作工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "2",
    name: "豆包",
    description: "字节跳动开发的免费AI聊天助手，支持多模态对话和内容生成",
    url: "https://www.doubao.com/",
    icon: "🤖",
    tags: ["AI对话工具", "AI助手"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "3",
    name: "Midjourney",
    description: "领先的 AI 图像生成工具，通过文字描述创建高质量艺术图像",
    url: "https://www.midjourney.com/",
    icon: "🎨",
    tags: ["AI图像工具", "AI创作工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "4",
    name: "Notion AI",
    description: "集成在 Notion 中的 AI 助手，帮助写作、总结、翻译和组织内容",
    url: "https://www.notion.so/product/ai",
    icon: "📝",
    tags: ["AI写作工具", "AI办公工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "5",
    name: "Runway",
    description: "专业的 AI 视频编辑和生成平台，支持视频生成、擦除、扩展等功能",
    url: "https://runwayml.com/",
    icon: "🎬",
    tags: ["AI视频工具", "AI创作工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "6",
    name: "Claude",
    description: "Anthropic 开发的 AI 助手，擅长长文本理解、分析和创作",
    url: "https://claude.ai/",
    icon: "🧠",
    tags: ["AI对话工具", "AI写作工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "7",
    name: "Stable Diffusion",
    description: "开源 AI 图像生成模型，支持本地部署和在线使用",
    url: "https://stability.ai/",
    icon: "🖼️",
    tags: ["AI图像工具", "AI创作工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "8",
    name: "讯飞星火",
    description: "科大讯飞开发的 AI 大模型，支持对话、写作、代码生成等功能",
    url: "https://xinghuo.xfyun.cn/",
    icon: "⭐",
    tags: ["AI对话工具", "AI助手"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "9",
    name: "文心一言",
    description: "百度开发的 AI 大语言模型，支持对话、创作、编程等场景",
    url: "https://yiyan.baidu.com/",
    icon: "🔥",
    tags: ["AI对话工具", "AI写作工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "10",
    name: "通义千问",
    description: "阿里巴巴开发的 AI 助手，支持多轮对话、内容创作和代码开发",
    url: "https://tongyi.aliyun.com/",
    icon: "💡",
    tags: ["AI对话工具", "AI办公工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "11",
    name: "Kimi 智能助手",
    description: "月之暗面开发的 AI 助手，擅长长文本理解和信息提取",
    url: "https://kimi.moonshot.cn/",
    icon: "🌙",
    tags: ["AI对话工具", "AI助手"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "12",
    name: "Canva AI",
    description: "Canva 的 AI 设计工具，支持 AI 生成图像、文案和设计建议",
    url: "https://www.canva.com/ai-image-generator/",
    icon: "🎨",
    tags: ["AI图像工具", "AI办公工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "13",
    name: "GitHub Copilot",
    description: "GitHub 和 OpenAI 合作的 AI 编程助手，智能代码补全和生成",
    url: "https://github.com/features/copilot",
    icon: "💻",
    tags: ["AI编程工具", "AI办公工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "14",
    name: "剪映",
    description: "字节跳动开发的视频编辑工具，内置 AI 剪辑、字幕生成等功能",
    url: "https://www.capcut.cn/",
    icon: "✂️",
    tags: ["AI视频工具", "AI创作工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "15",
    name: "Cursor",
    description: "AI 驱动的代码编辑器，支持对话式编程和智能代码生成",
    url: "https://cursor.sh/",
    icon: "🖱️",
    tags: ["AI编程工具", "AI办公工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "16",
    name: "DALL-E 3",
    description: "OpenAI 开发的 AI 图像生成模型，理解复杂提示并生成精准图像",
    url: "https://openai.com/dall-e-3",
    icon: "🎨",
    tags: ["AI图像工具", "AI创作工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "17",
    name: "秘塔写作猫",
    description: "AI 写作助手，支持文章创作、改写、翻译和润色",
    url: "https://xiezuocat.com/",
    icon: "🐱",
    tags: ["AI写作工具", "AI办公工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "18",
    name: "LiblibAI",
    description: "国内 AI 图像生成社区，提供 Stable Diffusion 模型和在线生成",
    url: "https://www.liblib.ai/",
    icon: "🌟",
    tags: ["AI图像工具", "AI学习网站"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "19",
    name: "智谱清言",
    description: "智谱 AI 开发的对话助手，支持多模态理解和内容生成",
    url: "https://chatglm.cn/",
    icon: "💬",
    tags: ["AI对话工具", "AI编程工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "20",
    name: "HeyGen",
    description: "AI 视频生成平台，支持数字人视频、多语言翻译视频制作",
    url: "https://www.heygen.com/",
    icon: "🎥",
    tags: ["AI视频工具", "AI创作工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "21",
    name: "DeepSeek",
    description: "深度求索 AI 助手，强大的中文大语言模型",
    url: "https://chat.deepseek.com/sign_in",
    icon: "🔍",
    tags: ["AI对话工具", "AI助手"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "22",
    name: "爱盘搜",
    description: "夸克网盘搜索引擎，快速查找网盘资源",
    url: "https://www.aipanso.com/",
    icon: "🔎",
    tags: ["网盘搜索", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "23",
    name: "趣盘搜",
    description: "专注夸克资源搜索的网盘搜索引擎",
    url: "https://pan.funletu.com/#/",
    icon: "📦",
    tags: ["网盘搜索", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "24",
    name: "Vidu AI",
    description: "全球领先的AI内容生产平台，视频生成工具",
    url: "https://www.vidu.cn/",
    icon: "🎬",
    tags: ["AI视频工具", "AI创作工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "25",
    name: "MiniMax Audio",
    description: "AI语音合成工具，创建逼真的语音",
    url: "https://www.minimax.io/audio",
    icon: "🎙️",
    tags: ["AI音频工具", "AI创作工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "26",
    name: "Suno AI",
    description: "AI音乐创作平台，轻松生成专属音乐作品",
    url: "https://www.suno.cn/home#/",
    icon: "🎵",
    tags: ["AI音频工具", "AI创作工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "27",
    name: "ComfyUI",
    description: "用AI生成视频、图像、音频的强大工具",
    url: "https://www.comfy.org/zh-cn/gallery",
    icon: "⚙️",
    tags: ["AI图像工具", "AI视频工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "28",
    name: "Hyper3D",
    description: "免费AI 3D模型生成器，从图像创建3D模型",
    url: "https://hyper3d.ai/?lang=zh",
    icon: "🧊",
    tags: ["AI图像工具", "3D工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "29",
    name: "沉浸式翻译",
    description: "新一代AI翻译软件，支持网页、PDF、视频翻译",
    url: "https://immersivetranslate.com/zh-Hans/download/",
    icon: "🌐",
    tags: ["AI办公工具", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "30",
    name: "remove.bg",
    description: "在线抠图软件，一键去除图片背景",
    url: "https://www.remove.bg/zh",
    icon: "✂️",
    tags: ["AI图像工具", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "31",
    name: "Lovart",
    description: "全球首个设计智能体，AI辅助设计工具",
    url: "https://www.lovart.ai/zh",
    icon: "🎨",
    tags: ["AI图像工具", "设计工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "32",
    name: "Element-Plus-X",
    description: "基于 Element Plus 的扩展组件库",
    url: "https://element-plus-x.com/zh/",
    icon: "💻",
    tags: ["开发工具", "前端框架"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "33",
    name: "shadcn/ui",
    description: "现代化的设计系统基础组件库",
    url: "https://ui.shadcn.com/",
    icon: "🎭",
    tags: ["开发工具", "UI组件"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "34",
    name: "Dribbble",
    description: "全球顶级设计师和创意专业人士社区",
    url: "https://dribbble.com/",
    icon: "🏀",
    tags: ["设计资源", "社区论坛"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "35",
    name: "PNG Images",
    description: "10万+免费PNG透明背景图片素材库",
    url: "https://pngimg.com/",
    icon: "🖼️",
    tags: ["设计资源", "素材库"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "36",
    name: "鸠摩搜索",
    description: "专业的文档搜索引擎，查找电子书和文档",
    url: "https://www2.jiumodiary.com/",
    icon: "📚",
    tags: ["网盘搜索", "学习平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "37",
    name: "SoBooks",
    description: "分享阅读乐趣的电子书资源站",
    url: "https://sobooks.cc/",
    icon: "📖",
    tags: ["学习平台", "电子书"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "38",
    name: "Class Central",
    description: "全球优质在线课程聚合平台",
    url: "https://www.classcentral.com/",
    icon: "🎓",
    tags: ["学习平台", "在线教育"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "39",
    name: "Upwork",
    description: "全球最大的自由职业者工作平台",
    url: "https://www.upwork.com/",
    icon: "💼",
    tags: ["在线工具", "兼职平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "40",
    name: "Fiverr",
    description: "自由职业服务市场，寻找全球顶尖人才",
    url: "https://www.fiverr.com/",
    icon: "🤝",
    tags: ["在线工具", "兼职平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "41",
    name: "腾讯混元3D",
    description: "腾讯开发的 AI 3D 模型生成工具，支持从文本或图像生成 3D 模型",
    url: "https://3d.hunyuan.tencent.com/",
    icon: "🧊",
    tags: ["AI图像工具", "3D工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "42",
    name: "Sketchfab Store",
    description: "全球最大的 3D 模型市场，提供海量免费和付费 3D 模型资源",
    url: "https://sketchfab.com/store",
    icon: "🎨",
    tags: ["设计资源", "3D工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "43",
    name: "TurboSquid",
    description: "专业级 3D 模型交易平台，为专业人士提供高质量 3D 资产",
    url: "https://www.turbosquid.com/",
    icon: "🖼️",
    tags: ["设计资源", "3D工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "44",
    name: "阿里1688",
    description: "阿里巴巴旗下批发采购平台，连接源头工厂和批发商",
    url: "https://www.1688.com/",
    icon: "🛒",
    tags: ["在线工具", "电商平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "45",
    name: "程序员客栈",
    description: "领先的程序员自由工作平台，提供程序员兼职和外包服务",
    url: "https://www.proginn.com/",
    icon: "💻",
    tags: ["在线工具", "兼职平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "46",
    name: "开源众包",
    description: "OSChina 旗下的项目众包平台，连接开发者和企业需求",
    url: "https://zb.oschina.net/projects/list.html",
    icon: "🤝",
    tags: ["在线工具", "兼职平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "47",
    name: "猿急送",
    description: "程序员兼职外包平台，快速匹配优质程序员资源",
    url: "https://www.yuanjisong.com/",
    icon: "🐒",
    tags: ["在线工具", "兼职平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "48",
    name: "MD2Card",
    description: "Markdown 转知识卡片工具，一键生成美观的知识分享卡片",
    url: "https://md2card.com/zh",
    icon: "📝",
    tags: ["AI办公工具", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "49",
    name: "Gemini",
    description: "Google DeepMind 开发的多模态 AI 模型，支持文本、图像、代码等多种任务",
    url: "https://deepmind.google/technologies/gemini/",
    icon: "💎",
    tags: ["AI对话工具", "AI助手"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "50",
    name: "MovieFlow",
    description: "AI 电影工作室，利用人工智能技术辅助视频创作和编辑",
    url: "https://movieflow.ai/",
    icon: "🎬",
    tags: ["AI视频工具", "AI创作工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "51",
    name: "AnyToCopy",
    description: "免费在线视频文案提取工具，支持抖音等 50+ 平台文案和音频提取",
    url: "https://www.anytocopy.com/",
    icon: "📋",
    tags: ["AI办公工具", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "52",
    name: "FreeConvert",
    description: "免费在线文件格式转换工具，支持图片、视频、文档等多种格式",
    url: "https://www.freeconvert.com/",
    icon: "🔄",
    tags: ["在线工具", "AI办公工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "53",
    name: "SnapAny",
    description: "万能视频图片解析下载工具，支持多平台内容下载",
    url: "https://snapany.com/zh",
    icon: "⬇️",
    tags: ["在线工具", "AI视频工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "54",
    name: "VDraw",
    description: "免费 AI 图像创作和视频编辑工具，简化内容创作流程",
    url: "https://vdraw.ai/",
    icon: "✏️",
    tags: ["AI图像工具", "AI视频工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "55",
    name: "Holopix AI",
    description: "游戏美术设计神器，低门槛高可控的 AI 设计解决方案",
    url: "https://holopix.cn/home",
    icon: "🎮",
    tags: ["AI图像工具", "设计工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "56",
    name: "呜哩AI",
    description: "一站式 AIGC 创意平台，提供多种 AI 创作工具",
    url: "https://wuli.art/generate",
    icon: "✨",
    tags: ["AI创作工具", "AI图像工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "57",
    name: "Pixian.AI",
    description: "免费在线图片背景移除工具，无需注册即可使用",
    url: "https://pixian.ai/",
    icon: "✂️",
    tags: ["AI图像工具", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "58",
    name: "Penpot",
    description: "开源设计与代码协作工具，支持团队协作和设计系统管理",
    url: "https://penpot.app/",
    icon: "🎨",
    tags: ["开发工具", "设计工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "59",
    name: "60fps",
    description: "UI/UX 动画灵感库，为移动和 Web 应用提供动画设计参考",
    url: "https://60fps.design/",
    icon: "🎬",
    tags: ["设计资源", "学习平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "60",
    name: "Mobbin",
    description: "移动应用设计灵感库，收录全球热门应用的 UI 设计模式",
    url: "https://mobbin.com/discover/sites/popular",
    icon: "📱",
    tags: ["设计资源", "学习平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "61",
    name: "火宝短剧",
    description: "基于 AI 的一站式短剧生成平台，一句话生成完整短剧，从剧本到成片全自动化",
    url: "https://github.com/chatfire-AI/huobao-drama",
    icon: "🎬",
    tags: ["AI视频工具", "AI创作工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "62",
    name: "RunningHub",
    description: "ComfyUI 工作流分享平台，提供声音克隆、多人对话等 AI 工作流",
    url: "https://www.runninghub.cn/",
    icon: "⚙️",
    tags: ["AI音频工具", "AI视频工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "63",
    name: "Voicebox",
    description: "开源语音克隆桌面应用，支持本地语音合成和克隆",
    url: "https://voicebox.sh/",
    icon: "🎙️",
    tags: ["AI音频工具", "开发工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "64",
    name: "Listnr",
    description: "AI 语音克隆和合成平台，30秒内克隆你的声音",
    url: "https://listnr.ai/voice-cloning",
    icon: "🗣️",
    tags: ["AI音频工具", "AI创作工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "65",
    name: "Apeaksoft 水印去除器",
    description: "在线图像编辑器，支持移除图片水印和编辑功能",
    url: "https://www.apeaksoft.com/zh-CN/watermark-remover/editor/",
    icon: "✏️",
    tags: ["AI图像工具", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "66",
    name: "LZL 在线工具",
    description: "免费在线批量图片转 SVG 工具，支持 JPG、PNG、GIF、ICON 等格式",
    url: "https://lzltool.cn/image2svg",
    icon: "🔄",
    tags: ["在线工具", "AI图像工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "67",
    name: "Barcode-Maker",
    description: "免费在线条形码生成器，快速创建各种类型的条形码",
    url: "https://barcode-maker.com/zh",
    icon: "📊",
    tags: ["在线工具", "AI办公工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "68",
    name: "theSVG",
    description: "提供 5645+ 免费品牌 SVG 图标，适合开发者和设计师使用",
    url: "https://www.thesvg.org/",
    icon: "🎨",
    tags: ["设计资源", "开发工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "69",
    name: "100font",
    description: "免费商用字体大全，提供安全可商用的字体下载",
    url: "https://www.100font.com/",
    icon: "🔤",
    tags: ["设计资源", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "70",
    name: "MFSC123",
    description: "免费商用素材站，提供可商用的图片、字体、模板等资源",
    url: "https://www.mfsc123.com/",
    icon: "📦",
    tags: ["设计资源", "素材库"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "71",
    name: "GreenVideo",
    description: "免费视频下载工具，支持 B站、抖音、YouTube 等多平台视频下载",
    url: "https://greenvideo.cc/",
    icon: "⬇️",
    tags: ["在线工具", "AI视频工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "72",
    name: "VideosDown",
    description: "专业视频下载工具，支持多种视频平台解析和下载",
    url: "https://wssp.eu.org/",
    icon: "📥",
    tags: ["在线工具", "AI视频工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "73",
    name: "VilVil",
    description: "视频图片解析下载工具，支持多平台内容提取",
    url: "https://downfuture.com/",
    icon: "🎞️",
    tags: ["在线工具", "AI视频工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "74",
    name: "飞牛 fnOS",
    description: "飞牛私有云操作系统，打造个人 NAS 和家庭数据中心",
    url: "https://www.fnnas.com/",
    icon: "💾",
    tags: ["开发工具", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "75",
    name: "响指 HaiSnap",
    description: "AI 零代码应用平台，人人都能创造 AI 应用",
    url: "https://www.haisnap.com/mobile",
    icon: "✨",
    tags: ["AI办公工具", "AI创作工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "76",
    name: "Same",
    description: "简约高效的社交应用，连接志同道合的朋友",
    url: "https://same.new/",
    icon: "💬",
    tags: ["社区论坛", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "77",
    name: "趣导航",
    description: "全网最实用简洁的网址导航，支持网址收录和分类检索",
    url: "https://qssily.com/",
    icon: "🧭",
    tags: ["在线工具", "学习平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "78",
    name: "502book",
    description: "免费小说搜索引擎，快速查找网络小说资源",
    url: "https://502book.com/",
    icon: "📚",
    tags: ["学习平台", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "79",
    name: "拼多多批发",
    description: "拼多多官方采购批发平台，源头好货一件也是批发价",
    url: "https://pifa.pinduoduo.com/",
    icon: "🛍️",
    tags: ["在线工具", "电商平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "80",
    name: "站长工具",
    description: "漫步白月光工具站，提供多种实用的站长工具和在线服务",
    url: "https://www.ccava.net/toolbox/5/",
    icon: "🔧",
    tags: ["开发工具", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "81",
    name: "浙江政务服务网",
    description: "浙江省政府政务服务平台，提供各类政务服务在线办理",
    url: "https://www.zjzwfw.gov.cn/zjservice-fe/#/home",
    icon: "🏛️",
    tags: ["在线工具", "AI办公工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "82",
    name: "Swagbucks",
    description: "在线调查和任务平台，完成任务赚取奖励",
    url: "https://search.swagbucks.com/?lang=zh",
    icon: "💰",
    tags: ["在线工具", "兼职平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "83",
    name: "UserTesting",
    description: "用户体验测试平台，提供产品可用性测试和洞察",
    url: "https://www.usertesting.com/",
    icon: "🧪",
    tags: ["在线工具", "兼职平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "84",
    name: "Teachable",
    description: "在线课程创建和销售平台，轻松打造自己的知识付费产品",
    url: "https://teachable.com/",
    icon: "🎓",
    tags: ["学习平台", "在线教育"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "85",
    name: "Amazon MTurk",
    description: "亚马逊众包平台，提供微任务和数据处理工作机会",
    url: "https://www.mturk.com/",
    icon: "🤖",
    tags: ["在线工具", "兼职平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "86",
    name: "SurveyJunkie",
    description: "在线调查平台，参与调查赚取积分和现金奖励",
    url: "https://lp.surveyjunkie.com/",
    icon: "📋",
    tags: ["在线工具", "兼职平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "87",
    name: "Cambly",
    description: "在线英语外教平台，随时随地与母语者练习英语口语",
    url: "https://www.cambly.com/english?lang=zh_CN",
    icon: "🗣️",
    tags: ["学习平台", "在线教育"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "88",
    name: "Voices",
    description: "全球领先的配音演员市场，雇佣专业配音人才",
    url: "https://www.voices.com/",
    icon: "🎙️",
    tags: ["在线工具", "兼职平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "89",
    name: "免费 AI 绘画提示词生成器",
    description: "AI 绘画提示词生成工具，帮助创作者优化 prompt",
    url: "https://prompt.krwoo.com/",
    icon: "💡",
    tags: ["AI图像工具", "AI创作工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "90",
    name: "imgchr",
    description: "路过图床-高速稳定的图片上传和外链服务,全球CDN加速, 支持外链, 原图保存, 最大单张支持5 MB,请遵守中国法律法规, 禁止上传色情/黑产等违法图片.",
    url: "https://imgchr.com/",
    icon: "🖼️",
    tags: ["图片托管", "免费图片上传", "图片分享"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "91",
    name: "Go 语言简明教程",
    description: "极客兔兔出品的 Go 语言快速入门教程，简洁易懂",
    url: "https://geektutu.com/post/quick-golang.html",
    icon: "📘",
    tags: ["学习平台", "开发工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "92",
    name: "京东易直播",
    description: "京东直播平台，提供电商直播和内容创作服务",
    url: "https://h5-elive.jd.com/",
    icon: "📺",
    tags: ["在线工具", "AI视频工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "93",
    name: "硬核指南",
    description: "够高清才是真硬核！提供高质量影视资源指南",
    url: "https://yinghezhinan.com/",
    icon: "🎬",
    tags: ["学习平台", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "94",
    name: "PinMe",
    description: "免费 IPFS 静态网站托管服务，去中心化前端部署方案",
    url: "https://pinme.eth.limo/",
    icon: "🌐",
    tags: ["开发工具", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "95",
    name: "aicofounder",
    description: "AI 创业助手，帮助你打造人们真正想要的产品",
    url: "https://aicofounder.com/",
    icon: "🚀",
    tags: ["AI办公工具", "AI创作工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "96",
    name: "PandaWiki",
    description: "现代化的知识库管理工具，支持团队协作和知识沉淀",
    url: "https://pandawiki.docs.baizhi.cloud/",
    icon: "📖",
    tags: ["AI办公工具", "学习平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "97",
    name: "Raycast API",
    description: "Raycast 扩展开发文档，构建强大的工作效率工具",
    url: "https://developers.raycast.com/basics/getting-started",
    icon: "⚡",
    tags: ["开发工具", "AI办公工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "98",
    name: "Stitch",
    description: "时尚艺术、工艺和纺织软件创新平台",
    url: "https://www.stitch.com/",
    icon: "🧵",
    tags: ["设计资源", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "99",
    name: "DC.js 工具库",
    description: "DarkCrystal 前端工具库，提供丰富的 UI 组件和工具函数",
    url: "https://dcjs.netlify.app/",
    icon: "💻",
    tags: ["开发工具", "UI组件"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "100",
    name: "Method of Action",
    description: "交互式设计和动画学习平台，通过实践掌握设计技能",
    url: "https://method.ac/",
    icon: "🎯",
    tags: ["学习平台", "设计资源"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "101",
    name: "Colors Combinations",
    description: "配色方案灵感库，提供丰富的色彩组合参考",
    url: "https://colors.combinations.obys.agency/",
    icon: "🎨",
    tags: ["设计资源", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "102",
    name: "Color Parrot",
    description: "颜色信息工具，提供详细的色彩数据和分析",
    url: "https://parrot.color.pizza/",
    icon: "🦜",
    tags: ["设计资源", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "103",
    name: "学种菜网",
    description: "蔬菜种植、水果粮食中药材种植技术及花卉养殖技巧知识大全",
    url: "https://m.xuezhongcai.com/",
    icon: "🌱",
    tags: ["学习平台", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "104",
    name: "七点工坊",
    description: "数字艺术与高端 CG 美术约稿交易平台，安全高效专业",
    url: "https://s.7games.com/",
    icon: "🎮",
    tags: ["设计资源", "兼职平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "105",
    name: "国家图书馆",
    description: "免费的在线图书馆，包含10万多本书籍，这包括小说、儿童书、心理学、美食、期刊杂志、美妆等分类",
    url: "https://www.nlc.cn/web/index.shtml",
    icon: "📚",
    tags: ["学习平台", "在线图书"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "106",
    name: "daisyUI",
    description: "基于 Tailwind CSS 的组件库，快速构建美观界面",
    url: "https://v2.daisyui.com/",
    icon: "🌼",
    tags: ["开发工具", "UI组件"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "107",
    name: "PayQrcode",
    description: "二合一收款码物理合并版，整合多种支付方式",
    url: "https://pay-qrcode.4ce.cn/",
    icon: "💳",
    tags: ["在线工具", "AI办公工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "108",
    name: "蒸汽游戏宝库",
    description: "高质量 Steam 单机游戏下载站，免费中文游戏整合包资源",
    url: "https://www.steambk.com/",
    icon: "🎮",
    tags: ["游戏平台", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "109",
    name: "微信公众号 Markdown 编辑器",
    description: "五大主题一键排版，支持实时预览复制粘贴",
    url: "https://www.md2wechat.com/",
    icon: "📝",
    tags: ["AI办公工具", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "110",
    name: "搬书匠",
    description: "电子书资源站，提供各类电子书下载",
    url: "http://www.banshujiang.cn/",
    icon: "📚",
    tags: ["学习平台", "电子书"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "111",
    name: "NO视频",
    description: "不负追剧好时光，提供影视资源在线观看",
    url: "https://www.novipnoad.cc/",
    icon: "🎬",
    tags: ["在线工具", "学习平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "112",
    name: "SVGcreator",
    description: "免费 SVG 转换工具，快速将图片转换为 SVG 格式",
    url: "http://svgcreator.com/",
    icon: "🔄",
    tags: ["在线工具", "设计资源"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "113",
    name: "MuleRun",
    description: "AI Agent 工作助手，自动化完成各种工作任务",
    url: "https://mulerun.com/",
    icon: "🤖",
    tags: ["AI办公工具", "AI助手"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "114",
    name: "小红书商机中心",
    description: "小红书官方商机发现平台，帮助创作者把握市场机会",
    url: "https://ark.xiaohongshu.com/app-item/opportunity/center",
    icon: "📊",
    tags: ["在线工具", "AI办公工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "115",
    name: "小红书创作服务平台",
    description: "小红书官方创作者平台，提供内容管理和数据分析",
    url: "https://creator.xiaohongshu.com/new/home",
    icon: "✍️",
    tags: ["在线工具", "社区论坛"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "116",
    name: "doyoudo",
    description: "创意设计学习平台，提供设计教程和灵感分享",
    url: "https://www.doyoudo.com/",
    icon: "🎨",
    tags: ["学习平台", "设计资源"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "117",
    name: "Code Guide",
    description: "AlloyTeam 出品的代码规范指南，提供前端开发最佳实践",
    url: "http://alloyteam.github.io/CodeGuide/",
    icon: "📖",
    tags: ["开发工具", "学习平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "118",
    name: "AI风月",
    description: "探索 AI 世界的精彩内容和应用案例",
    url: "https://distantalizing.xyz/zh",
    icon: "🌙",
    tags: ["AI学习网站", "社区论坛"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "119",
    name: "VUE后台管理系统模板",
    description: "基于 Vue.js 的后台管理系统模板，提供完整的管理界面解决方案",
    url: "http://vue.easydo.work/search.html",
    icon: "💻",
    tags: ["开发工具", "UI组件"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "120",
    name: "97盘搜",
    description: "网盘资源搜索平台，快速查找各类网盘分享资源",
    url: "https://pansoo.cn/",
    icon: "🔍",
    tags: ["网盘搜索", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "121",
    name: "维C搜搜",
    description: "好用的夸克资源搜索站，提供丰富的网盘资源检索服务",
    url: "https://vcsoso.com/",
    icon: "🔎",
    tags: ["网盘搜索", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "122",
    name: "KK分享笔记",
    description: "个人知识管理和分享平台，记录和学习各类知识",
    url: "https://www.kkpans.com/",
    icon: "📝",
    tags: ["学习平台", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "123",
    name: "爱盘",
    description: "最新的在线破解工具包，提供各类软件工具和资源",
    url: "https://down.52pojie.cn/",
    icon: "🔧",
    tags: ["开发工具", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "124",
    name: "Trymata",
    description: "网站测试和可用性测试平台，提供专业的用户体验测试服务",
    url: "https://trymata.com/",
    icon: "🧪",
    tags: ["在线工具", "兼职平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "125",
    name: "99designs",
    description: "全球领先的设计众包平台，连接设计师和企业客户",
    url: "https://99designs.com/designers",
    icon: "🎨",
    tags: ["设计资源", "兼职平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "126",
    name: "Textbroker",
    description: "内容创建和 SEO 服务机构，提供专业文案写作服务",
    url: "https://www.textbroker.com/",
    icon: "✍️",
    tags: ["在线工具", "兼职平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "127",
    name: "SolidGigs",
    description: "自由职业者线索自动化工具，帮助 freelancers 找到优质项目",
    url: "https://solidgigs.com/",
    icon: "💼",
    tags: ["在线工具", "兼职平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "128",
    name: "PlaytestCloud",
    description: "游戏测试平台，提供游戏可用性和玩家体验测试服务",
    url: "https://help.playtestcloud.com/",
    icon: "🎮",
    tags: ["在线工具", "游戏平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "129",
    name: "HDQWalls",
    description: "高清壁纸下载网站，提供最新最优质的桌面和手机壁纸",
    url: "https://hdqwalls.com/",
    icon: "🖼️",
    tags: ["设计资源", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "130",
    name: "Sprunki Retake",
    description: "Sprunki Incredibox 最新版本，音乐创作和混音平台",
    url: "https://sprunkiretake.net/",
    icon: "🎵",
    tags: ["AI音频工具", "游戏平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "131",
    name: "AIRI",
    description: "AI 助手平台，提供智能对话和任务自动化服务",
    url: "https://airi.moeru.ai/",
    icon: "🤖",
    tags: ["AI对话工具", "AI助手"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "132",
    name: "AI UI Designer",
    description: "AI UI 设计工具，60秒内生成完整的 UI 设计方案",
    url: "https://www.aiuidesigner.com/",
    icon: "🎨",
    tags: ["AI图像工具", "设计工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "133",
    name: "eu.org",
    description: "1996年运营至今，永久免费、无需续期，功能接近顶级域名，支持完整DNS记录类型，可托管到Cloudflare",
    url: "https://nic.eu.org",
    icon: "🌐",
    tags: ["域名", "DNS服务"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "134",
    name: "Cloudflare",
    description: "全球领先的DNS服务和CDN提供商，提供快速、安全、可靠的网络服务",
    url: "https://www.cloudflare.com/",
    icon: "☁️",
    tags: ["DNS服务", "CDN服务"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "135",
    name: "DNSHE / DNSBEE",
    description: "审核速度快（几分钟~几小时），支持完整DNS记录，可托管Cloudflare，新用户默认3个名额，邀请好友可增至5个",
    url: "https://dnshe.com",
    icon: "🌐",
    tags: ["域名", "DNS服务"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "136",
    name: "deSEC",
    description: "德国柏林非营利组织运营，隐私保护优先，原生支持DNSSEC，提供REST API + Terraform集成，全球Anycast网络解析延迟低",
    url: "https://desec.io",
    icon: "🌐",
    tags: ["域名", "DNS服务"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "137",
    name: "DigitalPlat",
    description: "支持GitHub账户验证后增加注册名额（1→2个），提供免费WHOIS隐私保护，支持托管Cloudflare",
    url: "https://digitalplat.org",
    icon: "🧊",
    tags: ["域名", "DNS服务"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "138",
    name: "DeepSeekMine",
    description: "DeepSeek 相关工具和资源集合",
    url: "https://deepseekmine.com/download",
    icon: "⛏️",
    tags: ["AI对话工具", "开发工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "139",
    name: "StackRyze",
    description: "界面简洁操作极简，最多可注册5个域名，支持托管Cloudflare，到期前60天邮件提醒续期",
    url: "https://domain.stackryze.com",
    icon: "🌐",
    tags: ["域名", "DNS服务"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "140",
    name: "Skills.sh",
    description: "Agent Skills 目录，AI 代理技能资源集合",
    url: "https://skills.sh/",
    icon: "🛠️",
    tags: ["开发工具", "AI助手"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "141",
    name: "Mock.js 文档",
    description: "Mock.js 是一款模拟数据生成器，帮助前端开发时模拟API响应",
    url: "https://github.com/nuysoft/Mock/wiki/Getting-Started",
    icon: "📝",
    tags: ["开发工具", "前端工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "142",
    name: "waifu2x",
    description: "图像超分辨率放大工具，在保持质量的同时放大图片",
    url: "http://waifu2x.udp.jp/",
    icon: "🖼️",
    tags: ["AI图像工具", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "143",
    name: "TypeScript 手册",
    description: "TypeScript 官方文档和手册，帮助学习和使用 TypeScript",
    url: "https://www.typescriptlang.org/docs/handbook/basic-types.html",
    icon: "📘",
    tags: ["开发工具", "学习平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "144",
    name: "W3School CSS 定位",
    description: "CSS 定位教程，学习网页布局和定位技术",
    url: "https://www.w3school.com.cn/css/css_positioning.asp",
    icon: "📐",
    tags: ["开发工具", "学习平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "145",
    name: "Vant 组件库",
    description: "轻量、可靠的移动端 Vue 组件库，用于快速构建移动应用",
    url: "https://vant-contrib.gitee.io/vant/#/zh-CN/quickstart",
    icon: "📱",
    tags: ["开发工具", "UI组件"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "146",
    name: "Vue CLI 配置",
    description: "Vue CLI 配置参考，用于定制 Vue 项目的构建配置",
    url: "https://cli.vuejs.org/zh/config/#devserver-proxy",
    icon: "⚙️",
    tags: ["开发工具", "前端工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "147",
    name: "TGideas 文档库",
    description: "腾讯 TGideas 设计文档库，提供设计规范和资源",
    url: "https://tgideas.qq.com/doc/",
    icon: "📚",
    tags: ["设计资源", "学习平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "148",
    name: "SteamDB",
    description: "Steam 数据库，提供 Steam 游戏和市场的详细信息",
    url: "https://steamdb.info/",
    icon: "🎮",
    tags: ["游戏平台", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "149",
    name: "酷家乐设计",
    description: "在线3D云设计软件，提供室内装修效果图和设计素材",
    url: "https://www.kujiale.com/",
    icon: "🏠",
    tags: ["设计资源", "3D工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "150",
    name: "MINE-H5-UI 组件库",
    description: "轻量级、模块化的 H5 前端 UI 组件库，基于 Vue 框架",
    url: "https://mineh5ui.biaov.cn/v2/doc/introduce",
    icon: "📱",
    tags: ["开发工具", "UI组件"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "151",
    name: "Element UI",
    description: "基于 Vue 的桌面端 UI 组件库，广泛应用于后台管理系统",
    url: "https://element.eleme.io/",
    icon: "📋",
    tags: ["开发工具", "UI组件"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "152",
    name: "uni-app 官网",
    description: "使用 Vue 语法开发跨平台应用的前端框架，支持多端部署",
    url: "https://uniapp.dcloud.io/resource?id=%e5%a6%82%e6%9e%9c%e4%bd%a0%e4%bd%bf%e7%94%a8%e8%bf%87mpvue",
    icon: "📱",
    tags: ["开发工具", "前端框架"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "153",
    name: "Crx搜搜",
    description: "支持 Chrome、Edge、火狐浏览器扩展和 Microsoft 应用商店软件搜索下载，资源丰富，下载速度快。",
    url: "https://www.crxsoso.com",
    icon: "🔌",
    tags: ["扩展商店", "开发工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "154",
    name: "VitePress 文档",
    description: "Vite 和 Vue 驱动的静态站点生成器，用于快速创建文档网站",
    url: "https://vitepress.vuejs.org/guide/getting-started.html",
    icon: "📝",
    tags: ["开发工具", "文档工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "155",
    name: "CodeFun",
    description: "UI 设计稿智能生成源代码工具，将设计稿快速转换为代码",
    url: "https://code.fun/",
    icon: "💻",
    tags: ["开发工具", "设计工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "156",
    name: "超级简历",
    description: "在线简历制作工具，提供多种模板帮助用户创建专业简历",
    url: "https://www.wondercv.com/cvs/Xj_GUP4/editor",
    icon: "📄",
    tags: ["AI办公工具", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "157",
    name: "Discord",
    description: "语音、视频和文字聊天平台，广泛用于社区和团队沟通",
    url: "https://discord.com/",
    icon: "💬",
    tags: ["社区论坛", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "158",
    name: "久久小说网",
    description: "TXT 小说下载网站，提供全本小说和免费电子书下载",
    url: "https://jjlxmc.com/",
    icon: "📖",
    tags: ["学习平台", "电子书"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "159",
    name: "魔笔小说",
    description: "在线小说阅读平台，提供连载中和完结的小说作品",
    url: "https://mobinovels.com/topics/continued/",
    icon: "📚",
    tags: ["学习平台", "电子书"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "160",
    name: "Pixiv 插画",
    description: "知名插画和漫画分享网站，提供大量原创艺术作品",
    url: "https://m.pixiv.vip/",
    icon: "🎨",
    tags: ["设计资源", "学习平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "161",
    name: "白鹭引擎文档",
    description: "白鹭引擎游戏开发文档，用于 HTML5 游戏开发",
    url: "https://docs.egret.com/engine/docs/installation/installation-plugin",
    icon: "🎮",
    tags: ["开发工具", "游戏平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "162",
    name: "思维导图工具",
    description: "在线思维导图工具，帮助整理思路和规划项目",
    url: "https://inspiring-golick-3c01b9.netlify.app/",
    icon: "🧠",
    tags: ["思维导图", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "163",
    name: "Vuetify.js",
    description: "基于 Vue.js 和 Material Design 的 UI 组件库",
    url: "https://vuetifyjs.com/zh-Hans/getting-started/quick-start/",
    icon: "📋",
    tags: ["开发工具", "UI组件"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "164",
    name: "Blender API 文档",
    description: "Blender 3D 建模和动画软件的 Python API 文档",
    url: "https://docs.blender.org/api/2.83/",
    icon: "🧊",
    tags: ["开发工具", "3D工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "165",
    name: "Wallhaven 壁纸",
    description: "高质量壁纸下载网站，提供大量精美壁纸资源",
    url: "https://wallhaven.cc/latest?page=2",
    icon: "🖼️",
    tags: ["设计资源", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "166",
    name: "CodePen 编辑器",
    description: "在线代码编辑器，支持实时预览前端代码效果",
    url: "https://codepen.io/pen/",
    icon: "💻",
    tags: ["开发工具", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "167",
    name: "StackBlitz",
    description: "在线 IDE 开发环境，支持快速创建和分享 Web 项目",
    url: "https://stackblitz.com/edit/js-nqf23e",
    icon: "💻",
    tags: ["开发工具", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "168",
    name: "MINE-H5-UI GitHub",
    description: "轻量级、模块化基于 VUE 的 H5 前端 UI 组件库开源项目",
    url: "https://github.com/biaov/MINE-H5-UI",
    icon: "📱",
    tags: ["开发工具", "UI组件"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "169",
    name: "InfoSpider 爬虫工具",
    description: "多功能爬虫工具箱，支持多种数据源的信息抓取",
    url: "https://github.com/kangvcar/InfoSpider",
    icon: "🕷️",
    tags: ["开发工具", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "170",
    name: "Go 语言文档",
    description: "Go 语言标准库文档中文版，方便学习和查询 Go 语言特性",
    url: "https://studygolang.com/pkgdoc",
    icon: "🐹",
    tags: ["开发工具", "学习平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "171",
    name: "Gin-Vue-Admin",
    description: "基于 Gin + Vue 的快速开发后台管理系统框架",
    url: "https://www.gin-vue-admin.com/docs/",
    icon: "⚙️",
    tags: ["开发工具", "前端框架"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "172",
    name: "Dribbble 作品",
    description: "设计师作品展示平台，提供大量创意设计灵感",
    url: "https://dribbble.com/shots",
    icon: "🎨",
    tags: ["设计资源", "学习平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "173",
    name: "Aerith Sheer Love Me Outfit With Sheer Stockings at Final Fantasy VII Remake Nexus - Mods and community",
    description: "Final Fantasy VII Remake 游戏模组社区",
    url: "https://www.nexusmods.com/finalfantasy7remake/mods/1019?tab=description",
    icon: "🎮",
    tags: ["游戏平台", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "174",
    name: "CloudNS",
    description: "老牌DNS服务商（2010年运营），免费额度：1域名+50条解析+50万次/月查询+1邮件转发，支持Anycast DNS",
    url: "https://www.cloudns.net",
    icon: "📝",
    tags: ["域名", "DNS服务", "SSL证书"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "175",
    name: "httprouter-GoDoc",
    description: "Go语言HTTP路由库文档",
    url: "https://godoc.org/github.com/julienschmidt/httprouter",
    icon: "🐹",
    tags: ["开发工具", "学习平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "176",
    name: "Gmail",
    description: "Google提供的电子邮件服务",
    url: "https://accounts.google.com/b/0/AddMailService",
    icon: "✉️",
    tags: ["在线工具", "AI办公工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "177",
    name: "TypeScript: Handbook - Basic Types",
    description: "TypeScript 官方文档和手册，帮助学习和使用 TypeScript",
    url: "https://www.typescriptlang.org/docs/handbook/basic-types.html",
    icon: "📘",
    tags: ["开发工具", "学习平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "178",
    name: "CSS 定位",
    description: "CSS 定位教程，学习网页布局和定位技术",
    url: "https://www.w3school.com.cn/css/css_positioning.asp",
    icon: "📐",
    tags: ["开发工具", "学习平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "179",
    name: "Vant - 轻量、可靠的移动端 Vue 组件库",
    description: "轻量、可靠的移动端 Vue 组件库，用于快速构建移动应用",
    url: "https://vant-contrib.gitee.io/vant/#/zh-CN/quickstart",
    icon: "📱",
    tags: ["开发工具", "UI组件"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "180",
    name: "地图",
    description: "Google Maps 地图服务",
    url: "https://maps.google.com/",
    icon: "🗺️",
    tags: ["在线工具", "AI办公工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "181",
    name: "MINE-H5-UI2",
    description: "轻量级、模块化的 H5 前端 UI 组件库，基于 Vue 框架",
    url: "https://mineh5ui.biaov.cn/v2/doc/introduce",
    icon: "📱",
    tags: ["开发工具", "UI组件"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "182",
    name: "Element - The world's most popular Vue UI framework",
    description: "基于 Vue 的桌面端 UI 组件库，广泛应用于后台管理系统",
    url: "https://element.eleme.io/",
    icon: "📋",
    tags: ["开发工具", "UI组件"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "183",
    name: "https://erogames.com/zh/games/craving-quest/play",
    description: "Craving Quest 游戏平台",
    url: "https://erogames.com/zh/games/craving-quest/play",
    icon: "🎮",
    tags: ["游戏平台", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "184",
    name: "如何学习 - uni-app官网",
    description: "使用 Vue 语法开发跨平台应用的前端框架，支持多端部署",
    url: "https://uniapp.dcloud.io/resource?id=%e5%a6%82%e6%9e%9c%e4%bd%a0%e4%bd%bf%e7%94%a8%e8%bf%87mpvue",
    icon: "📱",
    tags: ["开发工具", "前端框架"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "185",
    name: "Dev Sidecar",
    description: "DevSidecar是开发者必备的辅助工具，让GitHub访问不再是痛点。",
    url: "https://github.com/docmirror/dev-sidecar",
    icon: "🛠️",
    tags: ["辅助工具", "开发工具", "GitHub工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "186",
    name: "vue-awesome-swiper: Docs, Tutorials, Reviews | Openbase",
    description: "Vue.js 轮播组件库文档和教程",
    url: "https://openbase.com/js/vue-awesome-swiper",
    icon: "📱",
    tags: ["开发工具", "UI组件"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "187",
    name: "github-readme-stats/readme_cn.md at master · anuraghazra/github-readme-stats · GitHub",
    description: "GitHub 个人资料统计生成工具文档",
    url: "https://github.com/anuraghazra/github-readme-stats/blob/master/docs/readme_cn.md",
    icon: "📊",
    tags: ["开发工具", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "188",
    name: "Free Fonts for Commercial Use - Royalty Free | FontSpace",
    description: "提供可用于商业用途的免费字体资源",
    url: "https://www.fontspace.com/commercial-fonts?p=5",
    icon: "🔤",
    tags: ["设计资源", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "189",
    name: "p站-pixiv-插画世界",
    description: "知名插画和漫画分享网站，提供大量原创艺术作品",
    url: "https://m.pixiv.vip/",
    icon: "🎨",
    tags: ["设计资源", "学习平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "190",
    name: "动漫频道-热血国漫大全-正版热门动漫放送-腾讯视频",
    description: "腾讯视频动漫频道，提供正版动漫内容",
    url: "https://v.qq.com/channel/cartoon",
    icon: "🎬",
    tags: ["在线工具", "AI视频工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "191",
    name: "FormMaking",
    description: "在线表单制作工具",
    url: "https://form.making.link/basic-version/#/zh-CN/",
    icon: "📝",
    tags: ["AI办公工具", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "192",
    name: "[P站]-Pixiv Illustration Collection",
    description: "Pixiv 插画收藏网站",
    url: "https://pixivic.com/?VNK=5babbc95",
    icon: "🎨",
    tags: ["设计资源", "学习平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "193",
    name: "#オリジナル 寝起き白髪ちゃん - 林けゐ的插画 - pixiv",
    description: "Pixiv 上的原创插画作品",
    url: "https://www.pixiv.net/artworks/77583554",
    icon: "🎨",
    tags: ["设计资源", "学习平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "194",
    name: "大学生图像信息采集网",
    description: "中国大学生图像信息采集服务网站",
    url: "http://www.xinhuacu.com/#/home/submitPhoto/uploadPhoto",
    icon: "📸",
    tags: ["AI办公工具", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "195",
    name: "YouTube",
    description: "全球知名的视频分享平台",
    url: "https://youtube.com/",
    icon: "📺",
    tags: ["在线工具", "AI视频工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "196",
    name: "GitHub - biaov/MINE-H5-UI: 一款轻量级、模块化基于 VUE 的 H5 前端 UI 组件库 😊",
    description: "轻量级、模块化基于 VUE 的 H5 前端 UI 组件库开源项目",
    url: "https://github.com/biaov/MINE-H5-UI",
    icon: "📱",
    tags: ["开发工具", "UI组件"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "197",
    name: "\"BG-8A2FA02\", 7680x4800 Resolution Wallpaper ▪ Wallroom.io",
    description: "高质量壁纸下载网站",
    url: "https://wallroom.io/7680x4800/bg-8a2fa02",
    icon: "🖼️",
    tags: ["设计资源", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "198",
    name: "要求| Wiki.js",
    description: "Wiki.js 文档和安装要求",
    url: "https://docs.requarks.io/install/requirements",
    icon: "📖",
    tags: ["开发工具", "文档工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "199",
    name: "Dev:Py/Scripts/Cookbook - BlenderWiki",
    description: "Blender Python 脚本开发资源",
    url: "https://archive.blender.org/wiki/index.php/Dev:Py/Scripts/Cookbook/",
    icon: "🧊",
    tags: ["开发工具", "3D工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "200",
    name: "登录 — iKuuu VPN",
    description: "VPN 服务提供商",
    url: "https://ikuuu.ltd/auth/login",
    icon: "🔒",
    tags: ["在线工具", "开发工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "201",
    name: "Sora",
    description: "OpenAI 新一代AI音视频生成模型，首次实现了环境音效与画面动态的实时同步生成。",
    url: "https://sora.chatgpt.com/",
    icon: "🖼️",
    tags: ["AI视频工具", "AI创作工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "202",
    name: "vpn套餐详情",
    description: "VPN 服务提供商",
    url: "https://ouehr.top/",
    icon: "🔒",
    tags: ["在线工具", "开发工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "203",
    name: "One Small Step",
    description: "它不是教程，不是课程，就是一个技术概念速查手册。每个概念用一篇文章讲清楚，5分钟内读完。没有废话，没有凑字数，上来就是“是什么、为什么、有什么用”。",
    url: "github.com/karminski/one-small-step",
    icon: "📖",
    tags: ["开源项目", "新概念速查"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "204",
    name: "必剪",
    description: "B站官方出的剪辑软件，支持视频剪辑、合并、添加音乐、字幕等",
    url: "https://bcut.bilibili.cn/",
    icon: "🧪",
    tags: ["剪辑软件", "视频工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "205",
    name: "CapCut（剪映国际版）",
    description: "CapCut是剪映的国际版，同一个公司出的，操作逻辑一模一样，新手完全没学习成本。功能人声分离、降噪、智能抠图全免费，而且没有次数限制。",
    url: "capcut.com",
    icon: "🧪",
    tags: ["剪辑软件", "视频工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "206",
    name: "DaVinci Resolve",
    description: "DaVinci Resolve汇集剪辑、调色、视觉特效、动态图形和音频后期制作工具，以一套软件提供一站式解决方案！它采用美观新颖的界面设计，易学易用，能辅助新手用户快速上手操作，也能提供专业人士需要的强大性能。有了DaVinci Resolve，您无需学习使用多款软件工具，也不用在多款软件之间切换来完成不同的任务，从而以更快的速度制作出更优质的作品。这意味着您在制作全程都可以使用摄影机原始画质影像。只要一款软件，就相当于获得了属于您自己的后期制作工作室！学习和掌握DaVinci Resolve，就能获得好莱坞专业人士所使用的同款制作工具！",
    url: "http://www.blackmagicdesign.com/cn/products/davinciresolve",
    icon: "🧑‍💻",
    tags: ["视频工具", "后期制作"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "207",
    name: "AI Free Forever",
    description: "AI Free Forever 是一个免费的AI平台，无需注册，任何人都可以立即访问不断增长的AI工具集合，用于写作、图像生成、配音、转录、头脑风暴和日常生产力。无需注册、无需支付、无使用限制，只需打开即可使用。",
    url: "https://aifreeforever.com",
    icon: "🤖",
    tags: ["AI工具", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "208",
    name: "Aconvert",
    description: "Aconvert 是一个在线转换工具，支持多种文件格式转换，如MP4转AVI、MP3转WAV等。",
    url: "Aconvert.com",
    icon: "🎬",
    tags: ["在线工具", "转换工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "209",
    name: "Free LLM API Resources",
    description: "A collection of free LLM API resources",
    url: "https://github.com/cheahjs/free-llm-api-resources",
    icon: "🤝",
    tags: ["Free LLM API", "免费LLM资源"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "210",
    name: "Raphael AI",
    description: "Raphael AI 是一个免费、无限的 AI 图像生成器，通过 Z-Image、Flux 2、Qwen-Image 和 Nano Banana Pro 进行智能路由。无需注册，无限制。但是这些都是基本的功能，如果需要高级功能还是需要收费的。",
    url: "https://raphael.app/zh",
    icon: "🎬",
    tags: ["AI图像工具", "AI创作工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "211",
    name: "FMHY",
    description: "互联网上最大的免费资源集合站，20+ 个一级分类，3000+ 个经过验证的免费资源站",
    url: "https://fmhy.net/",
    icon: "💎",
    tags: ["在线导航", "资源汇总"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "212",
    name: "AI Video Maker",
    description: "AI 视频制作器：不限量生成 AI 视频。告别数积分，480p 免费不限量。订阅享 720p 不限量。仅在需要 1080p 与高级工具时才消耗积分。",
    url: "https://aivideomaker.ai/?ref=openi.cn",
    icon: "🎥",
    tags: ["AI视频工具", "AI创作工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "213",
    name: "Image to Prompt",
    description: "图片/文本转提示词（提示词生成工具），完全免费、可以无限生成、并且无需注册登录。ChatGPT 提示词生成器、Gemini 提示词生成器、Nano Banana 提示词生成器",
    url: "https://imagetoprompt.org/zh",
    icon: "💻",
    tags: ["提示词生成", "图片提示词"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "214",
    name: "NanoBananaPro提示词",
    description: "NanoBananaPro提示词、Seedance 2.0提示词、GPT Image 1.5 提示词、Seedream 4.5 提示词、Gemini 3 Pro 提示词生成工具，完全免费、可以无限生成、并且无需注册登录。",
    url: "https://youmind.com/zh-CN/",
    icon: "🤝",
    tags: ["提示词生成", "视频提示词"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "215",
    name: "DataTool",
    description: "在线视频下载工具。不过比一般的下载工具强的地方在于，它支持从全球超过50个主流平台下载视频，包括TikTok、YouTube、Instagram、B站、抖音、小红书这些大家常用的平台，都能一键解析下载。",
    url: "https://www.datatool.vip/zh",
    icon: "🐒",
    tags: ["视频下载", "视频去水印"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "216",
    name: "Blueprint",
    description: "通过与AI对话创建硬件原型设计",
    url: "https://www.blueprint.am/",
    icon: "📝",
    tags: ["硬件原型设计", "AI工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "217",
    name: "Awesome Cloudflare",
    description: "GitHub上一个精选Cloudflare资源合集，它只做一件事：帮独立开发者/个人站长/小团队，用最少时间、最低成本，把Cloudflare用到极致。",
    url: "https://github.com/zhuima/awesome-cloudflare",
    icon: "✂️",
    tags: ["Cloudflare", "使用指南"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "218",
    name: "Google AI Edge Gallery",
    description: "Google AI Edge Gallery就是一个让你在自个儿手机上，离线运行各种开源大模型的“沙盒”应用，现在已经正式支持最新的 Gemma 4 模型家族。",
    url: "https://github.com/google-ai-edge/gallery",
    icon: "🖱️",
    tags: ["AI工具", "离线运行"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "219",
    name: "Magic Resume （AI 求职利器）",
    description: "Magic Resume是一款现代化的在线 AI 简历编辑器，主打隐私安全与AI 辅助。它基于 TanStack Start、TypeScript 等现代技术栈构建，提供了所见即所得的编辑体验。最大的亮点在于：无需注册、无需登录，所有简历数据默认存储在本地浏览器中，彻底杜绝数据上云带来的隐私担忧。",
    url: "https://github.com/JOYCEQL/magic-resume",
    icon: "📝",
    tags: ["简历编辑", "AI工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "220",
    name: "Neovim 文件搜索神器",
    description: "fff.nvim，全称是 freakin fast fuzzy file finder，名字其实很直白，意思就是“非常快的模糊文件查找器”。它的目标不是简单替代已有工具，而是从底层重新思考“如何更高效地找到文件”。",
    url: "https://github.com/dmtrKovalenko/fff.nvim",
    icon: "🎨",
    tags: ["文件搜索", "Neovim插件"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "221",
    name: "JSON处理神器",
    description: "jq可以理解为“JSON 专用处理器”，就像 grep 处理文本一样，它专门用来处理 JSON 数据。",
    url: "https://github.com/jqlang/jq",
    icon: "✍️",
    tags: ["JSON处理", "命令行工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "222",
    name: "Maestro",
    description: "一个面向移动端和 Web 的端到端（E2E）自动化测试框架，支持 Android、iOS 以及 Web 应用，通过一套统一的方案完成测试编写与执行。",
    url: "https://github.com/mobile-dev-inc/Maestro",
    icon: "💼",
    tags: ["自动化测试", "移动测试", "Web测试"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "223",
    name: "PlaytestCloud常见问题新增内容 | PlaytestCloud帮助中心",
    description: "游戏测试平台，提供游戏可用性和玩家体验测试服务",
    url: "https://help.playtestcloud.com/en/collections/427900-new-to-playtestcloud-faqs",
    icon: "🎮",
    tags: ["在线工具", "游戏平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "224",
    name: "Fastfetch",
    description: "一个类似 neofetch 的系统信息获取工具，专注于高性能、丰富功能和高度可定制化。它使用 C 语言编写，在执行速度和资源占用方面表现非常优秀，同时支持多平台，包括 Linux、macOS、Windows 等。",
    url: "https://github.com/fastfetch-cli/fastfetch",
    icon: "🗣️",
    tags: ["系统信息", "命令行工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "225",
    name: "可我AI",
    description: "一键生成你的专属Q版/动漫/插画形象",
    url: "https://www.krwoo.com/",
    icon: "🎨",
    tags: ["AI图像工具", "AI创作工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "226",
    name: "动漫 - 网盘资源社 - 高质量网盘资源分享交流论坛！",
    description: "网盘资源分享交流论坛，提供高质量网盘资源",
    url: "https://by669.org/t/anime",
    icon: "🎬",
    tags: ["在线工具", "学习平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "227",
    name: "资源汇总",
    description: "各类资源汇总分享平台",
    url: "https://www.kdocs.cn/l/cmXCNN8bJtij",
    icon: "📁",
    tags: ["学习平台", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "228",
    name: "CheckIsSafe",
    description: "CheckIsSafe是一个在线工具和网址导航。它提供了一个简单易用的界面，用户可以输入网址并获取该网站的安全检查结果。",
    url: "https://checkissafe.netlify.app",
    icon: "💡",
    tags: ["个人网址", "开源工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "229",
    name: "Pretext",
    description: "Pretext是一款完全脱离 DOM、通过纯计算实现文本布局与尺寸测量的开源库，由知名开发者 Cheng Lou 打造，他曾是 React 核心团队成员，在前端工程化、渲染优化领域有着深厚的技术积累。",
    url: "https://github.com/chenglou/pretext",
    icon: "💻",
    tags: ["文本布局", "尺寸测量", "开源库"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "230",
    name: "Pixabay",
    description: "德国的老牌素材站，除了图片，还有矢量图、插画、视频、音乐，简直是素材界的超市。支持中文搜索，对国内用户很友好。",
    url: "https://www.pixabay.com/zh",
    icon: "⚙️",
    tags: ["素材站", "免费资源"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "231",
    name: "Pexels",
    description: "Pexels不仅有图片，还有视频素材（后面会说到）。图片库特别大，而且更新速度快，生活化、接地气的图片比较多。",
    url: "https://www.pexels.com/zh-cn",
    icon: "🖼️",
    tags: ["图片库", "免费资源"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "232",
    name: "Unsplash",
    description: "这应该是全球最火的免费图库了。图片质量是真的高，全是摄影师上传的原创作品，逼格满满。每天还会更新精选图片，涵盖了风景、人物、商务等各种类型。",
    url: "https://www.unsplash.com",
    icon: "🖼️",
    tags: ["图片库", "免费资源"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "233",
    name: "爱给网",
    description: "专注于视频模板、特效、音效、3D模型。Pr、AE、会声会影等模板都有。",
    url: "https://www.aigei.com",
    icon: "🎬",
    tags: ["视频素材", "音效素材", "3D模型"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "234",
    name: "Splitshire",
    description: "由网页设计师Danie Nanescu创建的专业素材库，提供高质量的免费图片和视频素材",
    url: "https://splitshire.com",
    icon: "⬇️",
    tags: ["素材库", "免费资源"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "235",
    name: "Mazwai",
    description: "新兴的视频素材站，由专业摄像师上传作品。航拍、城市、自然景观质量都很高。",
    url: "https://www.mazwai.com",
    icon: "🎬",
    tags: ["视频素材", "视频制作"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "236",
    name: "Coverr",
    description: "专门为网站背景视频设计的素材库，很多4K视频。旅游、自然、美食、办公等分类明确。",
    url: "https://www.coverr.co",
    icon: "🎬",
    tags: ["视频素材", "视频制作"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "237",
    name: "Mixkit",
    description: "除了视频，还有音乐、音效、视频模板。视频分类清晰，城市、人物、动物、科技等都有专门栏目。",
    url: "https://www.mixkit.co",
    icon: "🎬",
    tags: ["视频素材", "视频制作"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "238",
    name: "Freepik",
    description: "综合型素材网站，矢量图、PSD模板、图标、照片啥都有。设计感强，很多素材拿来就能用。",
    url: "https://www.freepik.com",
    icon: "🎬",
    tags: ["素材站", "免费资源"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "239",
    name: "Pexels Videos",
    description: "Pexels的视频版块，素材质量超高。生活、自然、城市、商务等各种类型都有，很多都是4K分辨率。",
    url: "https://www.pexels.com/videos",
    icon: "🎬",
    tags: ["视频素材", "视频制作"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "240",
    name: "蓝韵生活馆",
    description: "健康养生资讯网站",
    url: "https://zhidao.baidu.com/question/2087027231898780108.html",
    icon: "🌿",
    tags: ["在线工具", "学习平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "241",
    name: "Scoop",
    description: "A command-line installer for Windows",
    url: "https://scoop.sh/",
    icon: "📦",
    tags: ["命令行工具", "包管理工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "242",
    name: "Monaco Editor",
    description: "Monaco Editor is a browser-based code editor",
    url: "https://github.com/microsoft/monaco-editor",
    icon: "🎨",
    tags: ["代码编辑器", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "243",
    name: "만화 - 웹툰 - 레진코믹스",
    description: "韩国漫画和网络漫画平台",
    url: "https://www.lezhin.com/ko/bookshome?genre=_all&order=",
    icon: "📚",
    tags: ["在线工具", "学习平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "244",
    name: "FoodiesFeed",
    description: "专门做美食图片的网站，汉堡、咖啡、甜点...每一张都让人流口水。图片质量超高，拍得特别有食欲。",
    url: "https://www.foodiesfeed.com",
    icon: "🍔",
    tags: ["图片库", "免费资源"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "245",
    name: "Kaboompics",
    description: "由电商巨头Shopify出品，专门服务创业者和内容创作者。图片风格偏商业、生活、产品场景，很多带电商感，做带货内容特别合适。",
    url: "burst.shopify.com",
    icon: "💾",
    tags: ["图片库", "免费资源", "电商素材"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "246",
    name: "StockSnap",
    description: "小而美的精品图库，由独立摄影师团队运营。图片数量不算多，但张张精选，风格偏极简、高级感，适合做品牌视觉。",
    url: "https://www.isorepublic.com",
    icon: "✨",
    tags: ["图片库", "免费资源"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "247",
    name: "Picjumbo",
    description: "运营了10多年的老站，图片质量稳定。以唯美、清新风格为主，也有不少商务类图片。",
    url: "https://www.picjumbo.com",
    icon: "🌼",
    tags: ["图片库", "免费资源"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "248",
    name: "Switch520",
    description: "Switch 游戏资源分享平台，提供游戏下载和信息",
    url: "https://www.gamer520.com/",
    icon: "🎮",
    tags: ["游戏平台", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "249",
    name: "七点工坊-数字艺术与高端CG美术约稿交易平台-安全高效专业，助创作者打造品牌",
    description: "数字艺术与高端 CG 美术约稿交易平台，安全高效专业",
    url: "https://s.7games.com/",
    icon: "🎮",
    tags: ["设计资源", "兼职平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "250",
    name: "GitHub - LibreSpark/LibreTV: 一分钟搭建影视站，支持Vercel/Docker等部署方式",
    description: "开源项目，帮助快速搭建影视站，支持多种部署方式",
    url: "https://github.com/LibreSpark/LibreTV",
    icon: "🎬",
    tags: ["开发工具", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "251",
    name: "学种菜网-蔬菜种植_水果、粮食、中药材种植技术方法及花卉养殖技巧知识大全",
    description: "蔬菜种植、水果粮食中药材种植技术及花卉养殖技巧知识大全",
    url: "https://m.xuezhongcai.com/",
    icon: "🌱",
    tags: ["学习平台", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "252",
    name: "97盘搜 - 网盘资源搜索平台",
    description: "网盘资源搜索平台，快速查找各类网盘分享资源",
    url: "https://pansoo.cn/",
    icon: "🔍",
    tags: ["网盘搜索", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "253",
    name: "优酷 - 为好内容全力以赴",
    description: "中国知名视频播放平台，提供丰富视频内容",
    url: "https://www.youku.com/ku/webcomic",
    icon: "📺",
    tags: ["在线工具", "AI视频工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "254",
    name: "VUE后台管理系统模板",
    description: "基于 Vue.js 的后台管理系统模板，提供完整的管理界面解决方案",
    url: "http://vue.easydo.work/search.html?tag=go",
    icon: "💻",
    tags: ["开发工具", "UI组件"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "255",
    name: "小红书商机中心",
    description: "小红书官方商机发现平台，帮助创作者把握市场机会",
    url: "https://ark.xiaohongshu.com/app-item/opportunity/center?from=ark-login",
    icon: "📊",
    tags: ["在线工具", "AI办公工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "256",
    name: "VideosDown - 专业视频下载工具",
    description: "专业视频下载工具，支持多种视频平台解析和下载",
    url: "https://wssp.eu.org/",
    icon: "📥",
    tags: ["在线工具", "AI视频工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "257",
    name: "PNG images | 100 000+ Free PNG images",
    description: "10万+免费PNG透明背景图片素材库",
    url: "https://pngimg.com/",
    icon: "🖼️",
    tags: ["设计资源", "素材库"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "258",
    name: "GitHub - bilibili/Index-anisora",
    description: "Bilibili 动漫资源索引项目",
    url: "https://github.com/bilibili/Index-anisora",
    icon: "📺",
    tags: ["开发工具", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "259",
    name: "美少女壁纸合集 约20000+ - 网盘资源社 - 高质量网盘资源分享交流论坛！",
    description: "美少女壁纸资源合集，数量约20000+",
    url: "https://baoyu998.org/d/21060",
    icon: "🖼️",
    tags: ["设计资源", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "260",
    name: "高清美女套图大合集 60G 50多套 - 网盘资源社 - 高质量网盘资源分享交流论坛！",
    description: "高清美女图片套图资源合集，总容量60G，包含50多套",
    url: "https://baoyu998.org/d/20756",
    icon: "🖼️",
    tags: ["设计资源", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "261",
    name: "免费在线条形码生成器 - Barcode-Maker.com",
    description: "免费在线条形码生成器，快速创建各种类型的条形码",
    url: "https://barcode-maker.com/zh",
    icon: "📊",
    tags: ["在线工具", "AI办公工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "262",
    name: "🔥夸克小海洋每日更新资源大汇总🔥（持续更新）",
    description: "夸克网盘资源每日更新汇总，持续更新",
    url: "https://doc.bilistudy.com/",
    icon: "📂",
    tags: ["网盘搜索", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "263",
    name: "Colors Combinations",
    description: "配色方案灵感库，提供丰富的色彩组合参考",
    url: "https://colors.combinations.obys.agency/",
    icon: "🎨",
    tags: ["设计资源", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "264",
    name: "Color Parrot Companion — Color Information",
    description: "颜色信息工具，提供详细的色彩数据和分析",
    url: "https://parrot.color.pizza/",
    icon: "🦜",
    tags: ["设计资源", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "265",
    name: "《牧神记14》在线免费观看_全集完整版国漫动漫-樱喜影院",
    description: "国产动漫《牧神记》在线观看，提供全集完整版",
    url: "https://www.china-yinxi.com/xiplay/126032-0-13.html",
    icon: "🎬",
    tags: ["在线工具", "AI视频工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "266",
    name: "GPT与MBR转换-联想知识库",
    description: "关于GPT与MBR磁盘分区格式转换的技术说明",
    url: "https://iknow.lenovo.com.cn/detail/418199",
    icon: "💾",
    tags: ["开发工具", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "267",
    name: "Issues · flet-dev/flet · GitHub",
    description: "Flet 开发框架的 GitHub 问题跟踪页面",
    url: "https://github.com/flet-dev/flet/issues",
    icon: "🐛",
    tags: ["开发工具", "前端工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "268",
    name: "第188章 成神王后第一次闭关_吞噬星空2_笔趣阁",
    description: "网络小说《吞噬星空2》章节在线阅读",
    url: "https://m.juvmed.com/book/745007/215974155_5.html",
    icon: "📖",
    tags: ["学习平台", "电子书"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "269",
    name: "Sprunki Retake - The Latest Version of Sprunki Incredibox",
    description: "Sprunki Incredibox 最新版本，音乐创作和混音平台",
    url: "https://sprunkiretake.net/",
    icon: "🎵",
    tags: ["AI音频工具", "游戏平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "270",
    name: "视频图片解析下载 - VilVil",
    description: "视频图片解析下载工具，支持多平台内容提取",
    url: "https://downfuture.com/",
    icon: "🎞️",
    tags: ["在线工具", "AI视频工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "271",
    name: "OpenRouter",
    description: "大语言模型的统一界面更优价格,更高可用性,无需订阅。",
    url: "https://openrouter.ai/",
    icon: "💬",
    tags: ["AI工具", "API Key"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "272",
    name: "PocketBase",
    description: "PocketBase是一个用Go语言编写的开源后端解决方案，核心理念是'轻量级的全栈后端 in a box'，开箱即用。",
    url: "https://github.com/pocketbase/pocketbase",
    icon: "💻",
    tags: ["后端开发", "REST API接口"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "273",
    name: "快速开始 | BiliNote",
    description: "BiliNote快速入门指南，提供详细的使用说明和教程",
    url: "https://docs.bilinote.app/guide/quick-start.html",
    icon: "📘",
    tags: ["学习平台", "文档工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "274",
    name: "容器镜像服务 ACR 控制台",
    description: "阿里云容器镜像服务控制台，提供镜像管理和部署功能",
    url: "https://cr.console.aliyun.com/cn-hangzhou/instances/mirrors",
    icon: "📦",
    tags: ["开发工具", "云服务"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "275",
    name: "公众号",
    description: "微信公众号管理平台，用于内容发布和粉丝互动",
    url: "https://mp.weixin.qq.com/cgi-bin/appsg?begin=0&count=10&type=77&action=list_card&token=178832126&lang=zh_CN",
    icon: "📰",
    tags: ["社交媒体", "内容管理"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "276",
    name: "Home | Tunee | The First Music Agent of the World",
    description: "全球首个音乐代理平台，提供AI驱动的音乐创作服务",
    url: "https://www.tunee.ai/home",
    icon: "🎵",
    tags: ["AI音频工具", "音乐创作"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "277",
    name: "奇门风水大天师_作者:大茄子_爱下电子书",
    description: "在线小说阅读平台，提供风水题材小说",
    url: "https://ixdzs8.com/read/598279/",
    icon: "📖",
    tags: ["学习平台", "电子书"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "278",
    name: "风水堪舆-阳宅风水-家居风水-商铺风水-办公风水-玄空风水-风水化解方法-风水实用指南 - 神机阁",
    description: "风水知识学习平台，提供全方位风水堪舆指导",
    url: "https://www.shenjige.cn/fengshui/base",
    icon: "🏮",
    tags: ["学习平台", "传统文化"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "279",
    name: "周易bot",
    description: "周易占卜AI助手，提供传统易经咨询服务",
    url: "https://zhouyi.bot/",
    icon: "🔮",
    tags: ["AI助手", "传统文化"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "280",
    name: "算命免费,周公解梦,姓名测试打分,生肖运程_君子阁",
    description: "传统文化服务平台，提供算命、解梦、姓名测试等服务",
    url: "https://www.junzige.com/",
    icon: "🔮",
    tags: ["传统文化", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "281",
    name: "SVG动画生成器 – 使用AI在线创建和制作SVG动画 | SvgAnimate",
    description: "AI驱动的SVG动画生成工具，在线创建动态矢量图形",
    url: "https://www.svganimate.ai/zh/home",
    icon: "🎬",
    tags: ["AI图像工具", "设计工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "282",
    name: "Create Beautiful Designs | Aura",
    description: "设计工具平台，帮助用户创建美丽的视觉设计作品",
    url: "https://www.aura.build/",
    icon: "🎨",
    tags: ["设计资源", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "283",
    name: "GitHub - HTMLToolkit/HTMLRunner：一个很酷的实时HTML/JS运行工具，带控制台捕获功能。",
    description: "实时HTML/JS运行工具，带有控制台捕获功能，便于前端调试",
    url: "https://github.com/HTMLToolkit/HTMLRunner",
    icon: "💻",
    tags: ["开发工具", "前端工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "284",
    name: "HTMLRunner",
    description: "HTML/JS实时运行环境，支持即时预览和调试功能",
    url: "https://htmltoolkit.github.io/HTMLRunner/",
    icon: "💻",
    tags: ["开发工具", "前端工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "285",
    name: "HTML 在线编辑器（编译器、解释器和运行工具）",
    description: "在线HTML编辑器，集成了编译器、解释器和运行环境",
    url: "https://onecompiler.com/html",
    icon: "📝",
    tags: ["开发工具", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "286",
    name: "XD学习网-XDGAME_小刀教程网_汇聚全网学习视频教程资源下载",
    description: "综合学习资源网站，汇集各类视频教程和资源下载",
    url: "https://www.xuexi67.com/",
    icon: "📚",
    tags: ["学习平台", "在线教育"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "287",
    name: "GitHub - usestrix/strix: Open-source AI agents for penetration testing",
    description: "开源AI渗透测试工具，提供智能化安全测试功能",
    url: "https://github.com/usestrix/strix",
    icon: "🛡️",
    tags: ["开发工具", "安全工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "288",
    name: "GitHub - AstrBotDevs/AstrBot: Agentic IM Chatbot infrastructure that integrates lots of IM platforms, LLMs, plugins and AI features. ✨",
    description: "集成多种即时通讯平台的AI聊天机器人基础设施",
    url: "https://github.com/AstrBotDevs/AstrBot?tab=readme-ov-file",
    icon: "🤖",
    tags: ["AI助手", "开发工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "289",
    name: "Drawnix - 开源白板工具",
    description: "开源的在线白板工具，支持多人协作绘图",
    url: "https://drawnix.com/",
    icon: "📝",
    tags: ["设计工具", "协作工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "290",
    name: "VERT.sh",
    description: "在线转换工具平台，提供多种格式转换服务",
    url: "https://vert.sh/convert/",
    icon: "🔄",
    tags: ["在线工具", "格式转换"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "291",
    name: "星流 - 新一代设计Agent",
    description: "新一代AI设计助手，提供智能化设计服务",
    url: "https://www.xingliu.art/?sourceId=003811&msclkid=d66796e787141ef44d9aff9750ca1e79#bing&kid=74217574450707&k=%5B%E6%98%9F%E6%B5%81&campaign=569936300&adgroup=1187474447210558",
    icon: "🎨",
    tags: ["AI图像工具", "设计工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "292",
    name: "Honey Select 2 - 3D角色创建与互动游戏 | Illusion官方",
    description: "3D角色创建与互动游戏，提供虚拟角色体验",
    url: "https://hs2.uulumi.com/",
    icon: "🎮",
    tags: ["游戏平台", "3D工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "293",
    name: "Quickstart | Cursor Docs",
    description: "Cursor编辑器快速入门指南，提供详细的使用说明",
    url: "https://cursor.com/cn/docs/get-started/quickstart",
    icon: "🖱️",
    tags: ["开发工具", "文档工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "294",
    name: "背景音乐_音效素材免费下载-音素阁",
    description: "免费背景音乐和音效素材下载平台，提供多样化音频资源",
    url: "http://www.yinsuge.com/",
    icon: "🎵",
    tags: ["设计资源", "音频素材"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "295",
    name: "精校版TXT小说,免费有声小说,免费全本小说,完结小说排行榜-奥拉图小说",
    description: "提供精校版TXT小说、有声小说和完结小说的阅读平台",
    url: "http://www.aolatu.com/",
    icon: "📖",
    tags: ["学习平台", "电子书"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "296",
    name: "Flaticon",
    description: "全球最大的图标库，数百万个图标，PNG、SVG格式都有。",
    url: "https://www.flaticon.com",
    icon: "👻",
    tags: ["图标库", "免费资源"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "297",
    name: "casibase/casibase: ⚡️AI Cloud OS: Open-source enterprise-level AI knowledge base and MCP (model-context-protocol)/A2A (agent-to-agent) management platform with admin UI, user management and Single-Sign-On⚡️, supports ChatGPT, Claude, Llama, Ollama, HuggingFace, etc., chat bot demo: https://ai.casibase.com, admin UI demo: https://ai-admin.casibase.com",
    description: "开源企业级AI知识库和MCP管理平台，支持多种AI模型",
    url: "https://github.com/casibase/casibase",
    icon: "🧠",
    tags: ["AI工具", "开发工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "298",
    name: "Shoppe - Calicat",
    description: "Shopee电商设计平台，提供商品展示和购物服务",
    url: "https://www.calicat.cn/design/2034480206486020096?node-id=f381b5ce-3c01-4eca-aa21-ddcf9731e3b9&node-type=group&mode=design",
    icon: "🛍️",
    tags: ["在线工具", "电商平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "299",
    name: "Novu - Open-source notifications infrastructure for devs and product teams",
    description: "面向开发者和产品团队的开源通知基础设施",
    url: "https://novu.co/?utm_source=github&utm_campaign=readme",
    icon: "🔔",
    tags: ["开发工具", "通知服务"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "300",
    name: "TikTok Shop Seller Sign Up | Cross Border",
    description: "TikTok Shop跨境卖家注册平台，拓展全球电商市场",
    url: "https://seller.tiktokshopglobalselling.com/account/register?channel=douyin_bpo_jiaxiaoxue01",
    icon: "🛒",
    tags: ["电商平台", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "301",
    name: "快速入门 - Gradio 交互界面库",
    description: "Gradio交互界面库快速入门指南，简化AI模型部署",
    url: "https://gradio.org.cn/guides/quickstart",
    icon: "⚙️",
    tags: ["开发工具", "文档工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "302",
    name: "JoyPixels | Stunning emoji for beautiful brands & agencies!",
    description: "提供精美emoji表情包，用于品牌和机构美化设计",
    url: "https://joypixels.com/",
    icon: "😊",
    tags: ["设计资源", "表情包"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "303",
    name: "6000+ 在线 3D 样机 - 免费设计",
    description: "提供超过6000个在线3D样机模板，用于免费设计展示",
    url: "https://www.pacdora.cn/mockups",
    icon: "🧊",
    tags: ["设计资源", "3D工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "304",
    name: "免费在线拼图工具 - 免登录照片网格布局 & 海报制作 | 17拼图",
    description: "免登录的在线拼图工具，支持照片网格布局和海报制作",
    url: "https://pin.acg17.com/editor/zh/template/",
    icon: "🧩",
    tags: ["设计工具", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "305",
    name: "IFIXIT",
    description: "IFIXIT是一个提供手机、电脑等电子产品维修教程和零件的网站。",
    url: "https://zh.ifixit.com/",
    icon: "🎮",
    tags: ["维修教程", "电子产品"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "306",
    name: "GitHub",
    description: "全球最大的开源代码托管平台，提供代码托管、项目管理、代码审查等功能",
    url: "https://github.com",
    icon: "💻",
    tags: ["代码托管", "开源项目"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "307",
    name: "前端 UI 组件库搭建指南 - 知乎",
    description: "关于如何搭建前端 UI 组件库的技术文章",
    url: "https://zhuanlan.zhihu.com/p/94920464?from_voters_page=true",
    icon: "📘",
    tags: ["开发工具", "学习平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "308",
    name: "YouTube高清视频下载",
    description: "提供YouTube、Twitter (X)、Instagram、Facebook、TikTok、Vimeo、微博、抖音（虽然图里没写抖音，但通常这类工具都支持，或者支持西瓜/头条）、快手、B站、全民K歌、甚至陌陌、美拍等平台视频下载",
    url: "https://youtube.iiilab.com/",
    icon: "🎥",
    tags: ["视频下载", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "309",
    name: "Rule 34 - 1080p 1boy 1girl 1girls 3d anal anal grip anal penetration anal sex anal tugging animated anus ass athletic female backpussy balls balls deep beach big ass big penis black cat d.va blizzard entertainment bouncing ass breasts buttjob cum cum in ass cum inside cum on body cumshot d.va deep penetration detailed background ejaculation exhibitionism exposed exposed ass female female on top female penetrated gaping gaping anus grinding hana song hot dogging huge cock huge penis human large penis light-skinned male male male penetrating male penetrating female naked nude nude female outdoors overwatch penis penis out public public exposure pull out reverse cowgirl position riding riding penis sex short playtime sitting sitting on lap sitting on penis sitting on strapon small penis solo masturbation standing strapon strapon sex strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon strapon......",
    description: "成人内容网站，包含NSFW内容",
    url: "https://rule34.xxx/index.php?page=post&s=view&id=5974119&pool_id=22551",
    icon: "🔞",
    tags: ["游戏平台", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "310",
    name: "css3实现文字扫光渐变动画效果_Harrietjia的博客-CSDN博客_css文字扫光",
    description: "CSS3 文字扫光动画效果技术教程",
    url: "https://blog.csdn.net/qq_38188485/article/details/81260732",
    icon: "🎨",
    tags: ["开发工具", "学习平台"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "311",
    name: "PhET",
    description: "由美国科罗拉多大学开发的互动模拟网站，包含物理、化学、生物学等多个领域的模拟器",
    url: "https://phet.colorado.edu/",
    icon: "🧊",
    tags: ["模拟器", "教育工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "312",
    name: "小說",
    description: "小说阅读网站",
    url: "https://www.book18.org/#new",
    icon: "📖",
    tags: ["学习平台", "电子书"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "313",
    name: "哔哩哔哩 (゜-゜)つロ 干杯~-bilibili",
    description: "中国知名弹幕视频分享网站",
    url: "https://www.bilibili.com/",
    icon: "📺",
    tags: ["在线工具", "AI视频工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "314",
    name: "TrendRadar",
    description: "一款轻量、易部署的开源热点聚合工具，能一站式抓取今日头条、百度热搜、微博、抖音、知乎、B站等35+主流平台的实时热点，支持自定义关键词精准过滤，还能把结果推送到企业微信、飞书、钉钉、Telegram等常用工具，真正做到只看自己关心的内容，从被动接收算法推荐变成主动掌控信息源",
    url: "https://github.com/sansan0/TrendRadar",
    icon: "💬",
    tags: ["热点聚合", "开源工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "315",
    name: "Cutter",
    description: "这是一个由 Rizin 框架驱动的免费开源逆向工程平台，旨在为用户提供一个功能强大且用户友好的二进制分析环境。它继承了 Rizin（Radare2 的一个活跃分支）的强大分析能力，并将其封装在一个现代化的图形界面中。Cutter 的目标是让逆向工程变得更加高效、直观和易于访问。",
    url: "https://github.com/rizinorg/cutter",
    icon: "💻",
    tags: ["逆向工程", "开源工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "316",
    name: "GitHub",
    description: "基于 Sparc3D × Ultra3D 打造，生成可用于量产的 3D 模型，干净网格、可用几何、高细节",
    url: "https://www.hitem3d.ai/zh",
    icon: "🧊",
    tags: ["3D模型", "AI工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "317",
    name: "Image View",
    description: "在线文生图，需要配置模型API一起使用",
    url: "https://image.airymoon.com/",
    icon: "💻",
    tags: ["AI生图", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "318",
    name: "Gitee AI",
    description: "中国最大的开源代码托管平台，提供代码托管、项目管理、代码审查等功能,AI模型广场",
    url: "https://ai.gitee.com/serverless-api?model-vendor=deepseek#document_processing_label",
    icon: "💻",
    tags: ["AI模型", "代码托管"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "319",
    name: "Image Prompt",
    description: "图片转提示词生成器：一键生成 AI 图片描述与 Prompt，上传任意图片，快速生成适用于 Midjourney、DALL-E 3、Stable Diffusion、Flux 和 Nano Banana 的详细提示词或图片描述。免费、快速、无需登录。",
    url: "https://imageprompt.online/zh",
    icon: "💻",
    tags: ["AI工具", "提示词生成器", "图片转提示词"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "320",
    name: "EasySSub",
    description: "EasySub 是一款在线 AI 字幕生成器。 它提供AI语音识别、AI字幕生成、AI字幕翻译，本来就很简单的视频剪辑。",
    url: "https://easyssub.com/price/",
    icon: "💻",
    tags: ["AI工具", "字幕生成"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "321",
    name: "HuggingFace",
    description: "全球最大AI模型下载网址",
    url: "https://huggingface.co/huggingface",
    icon: "💻",
    tags: ["AI模型", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "322",
    name: "Civitai",
    description: "Civitai 是一个提供AI模型下载的网站，支持语音识别、语音合成、图像识别、自然语言处理等服务，用户可以上传和下载模型",
    url: "https://civitai.com/",
    icon: "💻",
    tags: ["AI模型", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "323",
    name: "Netlify",
    description: "Netlify 是一个流行的静态网站托管服务，提供快速、可靠的网站托管和部署解决方案。",
    url: "https://app.netlify.com/",
    icon: "💻",
    tags: ["静态网站托管", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "324",
    name: "Yandex",
    description: "一个流行的搜索引擎",
    url: "https://yandex.com/",
    icon: "💻",
    tags: ["搜索引擎", "在线工具"],
    stats: { views: 0, likes: 0 },
  },
  {
    id: "325",
    name: "Remix Icons",
    description: "3200+ 图标，Apache 2.0 协议，支持 Outline/Solid 风格，类目齐全，棱角风格鲜明。",
    url: "https://remixicon.com",
    icon: "😊",
    tags: ["图标库", "棱角风格", "类目全面"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "326",
    name: "Tabler Icons",
    description: "4985 图标，MIT 协议，支持 Outline/Solid 风格，数量大，中性风格。",
    url: "https://tabler.io/icons",
    icon: "😊",
    tags: ["图标库", "数量大", "中性设计"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "327",
    name: "Phosphor Icons",
    description: "9072 图标，MIT 协议，支持 Outline/Solid/Duotone 风格，最大图标库，提供 4 种粗细调节。",
    url: "https://phosphoricons.com",
    icon: "😊",
    tags: ["图标库", "最大库", "多风格"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "328",
    name: "Heroicons",
    description: "316 图标，MIT 协议，支持 Outline/Solid 风格，Tailwind 出品，圆润饱满。",
    url: "https://heroicons.com",
    icon: "😊",
    tags: ["Tailwind", "圆润风格", "图标库"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "329",
    name: "Lucide Icons",
    description: "1668 图标，MIT 协议，Outline 风格，Shadcn/ui 默认图标库，线条轻盈。",
    url: "https://lucide.dev",
    icon: "😊",
    tags: ["Shadcn", "轻盈现代", "图标库"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "330",
    name: "Ming Cute Icons",
    description: "3000+ 图标，Apache 2.0 协议，支持 Outline/Solid 风格，类目独特，覆盖范围广。",
    url: "https://mingcute.com",
    icon: "😊",
    tags: ["图标库", "类目独特", "覆盖面广"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "331",
    name: "Iconoir",
    description: "1500+ 图标，MIT 协议，Outline 风格，曾被 HBO 使用，设计简洁。",
    url: "https://iconoir.com",
    icon: "😊",
    tags: ["图标库", "简洁", "Outline"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "332",
    name: "Material Icons",
    description: "2000+ 图标，Apache 2.0 协议，支持 Outline/Solid 风格，谷歌出品，可高度定制。",
    url: "https://fonts.google.com/icons",
    icon: "😊",
    tags: ["图标库", "可定制", "Material Design"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "333",
    name: "Glow Icons",
    description: "442 图标，MIT 协议，支持 Outline/Solid 风格，精选常用图标，开箱即用。",
    url: "https://glowui.com/icons",
    icon: "😊",
    tags: ["图标库", "开箱即用", "轻量"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "334",
    name: "Kdenlive",
    description: "专业级非线性视频编辑器，适用于严肃的多轨道剪辑和长片项目。支持无限音视频轨道，拥有强大的效果库和可定制界面。跨平台支持 Windows、macOS 和 Linux。",
    url: "https://kdenlive.org",
    icon: "📺",
    tags: ["专业级", "多轨道剪辑", "跨平台"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "335",
    name: "OpenShot",
    description: "极其简单、用户友好的免费开源视频编辑器，无学习曲线，适合绝对初学者。具有拖放功能、关键帧动画和内置效果，对系统资源要求极低。",
    url: "https://openshot.org",
    icon: "📺",
    tags: ["初学者友好", "界面简洁", "轻量级"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "336",
    name: "Shotcut",
    description: "在简单性、稳定性和广泛格式支持之间取得最佳平衡。支持海量音视频格式（基于FFmpeg），提供滤镜和效果，可在性能较弱的硬件上运行。",
    url: "https://shotcut.org",
    icon: "📺",
    tags: ["格式支持广", "稳定可靠", "跨平台"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "337",
    name: "Blender",
    description: "世界一流的3D创作套件，内置强大的视频序列编辑器（VSE）。适合将视频编辑与3D图形、视觉效果结合的创作者，支持高级合成和绿幕处理。",
    url: "https://blender.org",
    icon: "📺",
    tags: ["3D集成", "视觉效果", "功能强大"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "338",
    name: "DaVinci Resolve",
    description: "专业级免费视频编辑器（非开源），提供好莱坞级别的剪辑、色彩校正（行业标准调色）、视觉特效（Fusion）和音频后期（Fairlight）一体化流程。需要高端硬件。",
    url: "https://www.blackmagicdesign.com/products/davinciresolve",
    icon: "📺",
    tags: ["专业级", "调色标杆", "一体化流程"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "339",
    name: "Flowblade",
    description: "为Linux设计的轻量级多轨道非线性编辑器，专注快速流畅的剪辑工作流程。界面干净、响应迅速，非常适合快速视频项目。",
    url: "http://flowblade.sourceforge.net",
    icon: "📺",
    tags: ["Linux原生", "快速工作流", "轻量级"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "340",
    name: "Olive",
    description: "相对较新的跨平台开源视频编辑器，拥有时尚现代的界面，专注实时播放和响应速度。仍处于早期开发阶段，但展现出巨大潜力。",
    url: "https://olivevideoeditor.org",
    icon: "📺",
    tags: ["现代界面", "响应迅速", "新兴项目"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "341",
    name: "Avidemux",
    description: "用于快速剪辑、过滤和编码的轻量级工具，并非非线性编辑器。极其稳定可靠，适合简单快速的视频处理任务，如裁剪片段、添加滤镜或转换格式。",
    url: "http://avidemux.sourceforge.net",
    icon: "📺",
    tags: ["快速剪辑", "轻量级", "格式转换"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "342",
    name: "Pitivi",
    description: "为Linux设计的简单直观的非线性编辑器，注重易用性。提供剪切、修整和基本时间线功能，非常适合基础视频项目和初学者。",
    url: "http://pitivi.org",
    icon: "📺",
    tags: ["Linux原生", "初学者友好", "界面直接"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "343",
    name: "VidCutter",
    description: "专注于快速无损剪切和拼接视频片段的轻量级工具。具有极简界面，支持硬件加速播放和“SmartCut”功能，适合快速修剪或合并片段。",
    url: "https://vidcutter.ozmartians.com",
    icon: "📺",
    tags: ["无损剪切", "极速拼接", "轻量级"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "344",
    name: "Natron",
    description: "强大的基于节点的开源视频合成软件，专注于视觉效果和合成（类似Nuke）。支持2D/2.5D合成、绿幕抠像、动态遮罩和2D跟踪，适合VFX艺术家。",
    url: "https://natrongithub.github.io",
    icon: "📺",
    tags: ["节点合成", "视觉效果", "专业级"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "345",
    name: "LiVES",
    description: "独特的开源视频编辑器，结合了实时视频表演（VJing）与非线性编辑。支持使用键盘或MIDI控制器混合片段并应用实时效果，帧和样本精确。",
    url: "http://lives-video.com",
    icon: "📺",
    tags: ["VJ表演", "实时混合", "Linux原生"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "346",
    name: "AI-Scientist-v2",
    description: "AI自动做科研写论文，从提出想法、文献搜索、实验设计到撰写论文全程自动化。生成论文已通过ICLR 2025同行评审，成果发表在Nature上。采用渐进式Agent树搜索，内置自动评审器。",
    url: "https://github.com/SakanaAI/AI-Scientist-v2",
    icon: "🤖",
    tags: ["AI科研", "自动化", "Nature发表"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "347",
    name: "VibeVoice",
    description: "微软开源语音AI模型家族，包含TTS和ASR。TTS单次生成90分钟多说话人音频，ASR单次处理60分钟音频。提供0.5B参数的轻量级实时TTS模型，延迟约300ms。",
    url: "https://github.com/microsoft/VibeVoice",
    icon: "🎙️",
    tags: ["语音合成", "语音识别", "长音频处理"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "348",
    name: "Hermes Agent",
    description: "自学习AI Agent框架，具有闭环学习系统，能自动提炼经验为可复用技能。支持200多个模型，可对接飞书、企业微信等十几个平台。",
    url: "https://github.com/NousResearch/hermes-agent",
    icon: "🔄",
    tags: ["AI Agent", "自学习", "多平台对接"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "349",
    name: "Onyx",
    description: "开源企业AI搜索工具（原Danswer），打通GitHub、Google Drive、Confluence、Slack等数据源。支持Deep Research、代码沙箱、语音模式，可完全自托管。",
    url: "https://github.com/onyx-dot-app/onyx",
    icon: "🔍",
    tags: ["企业搜索", "RAG", "自托管"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "350",
    name: "claude-howto",
    description: "超全Claude Code学习指南，10个教程模块总时长11-13小时。提供生产级模板和可视化教程，可生成EPUB电子书离线查看。",
    url: "https://github.com/luongnv89/claude-howto",
    icon: "📘",
    tags: ["Claude Code", "学习指南", "教程"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "351",
    name: "oh-my-claudecode",
    description: "Claude Code的多Agent编排系统，提供19个专业化Agent（架构师、规划师、执行者等）。支持智能模型路由节省30-50% Token，具有Skill学习系统。",
    url: "https://github.com/Yeachan-Heo/oh-my-claudecode",
    icon: "🧩",
    tags: ["Claude Code", "多Agent", "编排系统"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "352",
    name: "oh-my-codex",
    description: "OpenAI Codex CLI的多Agent编排系统，提供30个专业Agent和40多个Skill。支持最多20个Worker并行工作，可混合使用Codex和Claude模型。",
    url: "https://github.com/Yeachan-Heo/oh-my-codex",
    icon: "⚡",
    tags: ["OpenAI Codex", "并行处理", "多Agent"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "353",
    name: "last30days-skill",
    description: "Claude Code/Codex CLI的Skill，一句话搜遍Reddit、X、YouTube等10个平台最近30天讨论。支持比较模式，自动生成带引用研究报告。",
    url: "https://github.com/mvanhorn/last30days-skill",
    icon: "📊",
    tags: ["信息搜索", "趋势分析", "Claude Skill"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "354",
    name: "OpenScreen",
    description: "Screen Studio的开源免费替代品，支持屏幕录制、自动缩放平移、动态模糊、标注添加。一键输出专业Demo视频效果，支持三大操作系统。",
    url: "https://github.com/siddharthvaddem/openscreen",
    icon: "🎥",
    tags: ["屏幕录制", "开源替代", "视频美化"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "355",
    name: "TaxHacker",
    description: "AI自动记账算税工具，拍照或上传PDF发票自动提取商品名称、金额、税额等信息。支持170+法定货币和14种加密货币汇率换算，支持本地LLM离线运行。",
    url: "https://github.com/vas3k/TaxHacker",
    icon: "💰",
    tags: ["自动记账", "税务处理", "本地LLM"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "356",
    name: "TimesFM",
    description: "Google Research时序预测基础模型，在1000亿时间点预训练。2.5版本仅200M参数，零样本预测准确率高，上下文窗口支持16384时间步。",
    url: "https://github.com/google-research/timesfm",
    icon: "📈",
    tags: ["时序预测", "Google", "轻量级"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "357",
    name: "LongCat-Flash-Prover",
    description: "美团开源数学定理证明模型，将证明拆解为形式化翻译、草稿规划、补全证明三步。MiniF2F-Test达97.1%，开源模型SOTA。内置语法分析器检测AI作弊。",
    url: "https://github.com/meituan-longcat/LongCat-Flash-Prover",
    icon: "🔢",
    tags: ["数学定理证明", "美团", "Lean4"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "358",
    name: "MoneyPrinterTurbo",
    description: "一键生成短视频工具，给定主题自动生成文案、配音、字幕、背景音乐。支持12+大模型接入，提供Web界面和REST API，Docker一键部署。",
    url: "https://github.com/harry0703/MoneyPrinterTurbo",
    icon: "🎬",
    tags: ["视频生成", "自媒体", "自动化"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "359",
    name: "Supermemory",
    description: "AI持久记忆引擎，在三大AI记忆基准测试中全部排名第一。自动从对话提取事实并管理，混合RAG+Memory检索，支持多平台数据同步。",
    url: "https://github.com/supermemoryai/supermemory",
    icon: "🧠",
    tags: ["AI记忆", "RAG", "上下文管理"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "360",
    name: "Pascal Editor",
    description: "浏览器内3D建筑设计编辑器，支持墙体、楼板、门窗拖拽操作和多楼层管理。基于React Three Fiber + WebGPU，提供碰撞检测和50步撤销重做。",
    url: "https://github.com/pascalorg/editor",
    icon: "🏠",
    tags: ["3D设计", "建筑设计", "浏览器内"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "361",
    name: "MoneyPrinterV2",
    description: "自动化在线赚钱工具集，集成Twitter机器人、YouTube Shorts自动化、联盟营销、本地商家挖掘等功能。用AI生成图像替代库存视频，支持CRON定时执行。",
    url: "https://github.com/FujiwaraChoki/MoneyPrinterV2",
    icon: "🖨️",
    tags: ["自动化", "内容生成", "赚钱工具"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "362",
    name: "Project N.O.M.A.D.",
    description: "完全离线的知识教育服务器，打包Ollama本地AI、离线维基百科、Khan Academy课程和离线地图。一键Docker部署，零遥测，适合离网环境。",
    url: "https://github.com/Crosstalk-Solutions/project-nomad",
    icon: "🏕️",
    tags: ["离线教育", "知识服务器", "隐私保护"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "363",
    name: "moondream",
    description: "超小视觉语言模型，仅1GB可在笔记本/边缘设备运行图像描述、物体检测、文档阅读。通过pip安装即可使用，平衡了精度和效率。",
    url: "https://github.com/vikhyat/moondream",
    icon: "🌙",
    tags: ["视觉语言模型", "轻量级", "本地运行"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "364",
    name: "everything-claude-code",
    description: "Claude Code完整配置合集，包括agents、skills、hooks、commands、rules等生产级配置。Anthropic hackathon获奖项目，可快速搭建AI代码助手。",
    url: "https://github.com/affaan-m/everything-claude-code",
    icon: "📦",
    tags: ["Claude Code", "配置合集", "代码助手"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "365",
    name: "agent-browser",
    description: "Vercel Labs出品的无头浏览器自动化CLI，专为AI Agent设计。Rust核心+Node fallback，比Playwright省上下文82%，支持网页自动操作。",
    url: "https://github.com/vercel-labs/agent-browser",
    icon: "🕸️",
    tags: ["浏览器自动化", "AI Agent", "Vercel"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "366",
    name: "planning-with-files",
    description: "Claude Code插件，实现文件驱动的持久化Markdown规划（类似Manus工作流）。将计划、进度、知识存磁盘，多轮任务不丢上下文。",
    url: "https://github.com/OthmanAdi/planning-with-files",
    icon: "📋",
    tags: ["Claude Code", "任务规划", "文件持久化"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "367",
    name: "kreuzberg",
    description: "Rust核心的多格式文档提取引擎，支持PDF、Office、图像等50+格式，提取文本/元数据/结构化信息。适合本地RAG知识库，零GPU运行。",
    url: "https://github.com/kreuzberg-dev/kreuzberg",
    icon: "📄",
    tags: ["文档提取", "RAG", "Rust"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "368",
    name: "DeepTutor",
    description: "港大出品的AI个性化学习助手，支持上传文档构建知识库，多Agent交互教学。不仅给答案还会反问引导，帮助自学和面试刷题。",
    url: "https://github.com/HKUDS/DeepTutor",
    icon: "🎓",
    tags: ["AI教学", "学习助手", "多Agent"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "369",
    name: "Anime Scene Search Engine",
    description: "专业动漫截图搜索引擎，识图找动漫必备！我们可以点击文件夹图标上传截图、将图片拖入页面、粘贴图片链接三种方式上传图片。",
    url: "https://trace.moe",
    icon: "💬",
    tags: ["识图", "找动漫"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "370",
    name: "通用媒体下载器",
    description: "免费简洁的多平台视频下载工具。支持 B 站、抖音、小红书的音频、视频、图文解析下载。在输入框中粘贴视频链接后，点击解析按钮，即可选择视频或音频开始下载。无需注册登录，完全免费，不限下载次数，手机和电脑都能使用。",
    url: "https://downloader.bhwa233.com/zh",
    icon: "💬",
    tags: ["多平台", "视频下载"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "371",
    name: "PDF24",
    description: "PDF工具，支持PDF创建、编辑、转换、合并、分割、加密、解密、旋转、添加水印、删除页面、提取文本、提取图片、PDF转Word、PDF转Excel、PDF转PPT、Word转PDF、Excel转PDF、PPT转PDF。",
    url: "https://tools.pdf24.org/zh/",
    icon: "💬",
    tags: ["PDF工具", "文档处理", "在线转换"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "372",
    name: "ai-money-maker-handbook",
    description: "这是一个关于用AI搞副业赚钱的实战手册，说白了就是教你如何利用AI技术（比如做自媒体、开发小产品）在业余时间赚取额外收入。它收集了大量的案例、工具和平台信息，特别适合想搞副业但不知道从哪下手的开发者或内容创作者。",
    url: "https://github.com/XiaomingX/ai-money-maker-handbook",
    icon: "💬",
    tags: ["AI变现", "副业", "赚钱工具"],
    stats: { views: 0, likes: 0 }
  },
  {
    id: "373",
    name: "Photopea",
    description: "在线修图工具，无需安装。支持PSD/AI/Sketch等专业格式，功能对标Photoshop，包含图层、蒙版、滤镜等，完全免费，无广告无水印，操作在本地完成。",
    url: "https://www.photopea.com",
    icon: "🎨",
    tags: ["图片编辑", "在线工具", "设计师必备"],
    stats: {
      views: 0,
      likes: 0
    }
  },
  {
    id: "374",
    name: "Krita",
    description: "自由开源的免费数字绘画软件。适合概念图、插画、漫画、动画制作。支持数位板压感、图层、滤镜，内置完整官方中文支持。",
    url: "https://krita.org/zh/",
    icon: "✍️",
    tags: ["绘画", "开源", "动画制作"],
    stats: {
      views: 0,
      likes: 0
    }
  },
  {
    id: "375",
    name: "OBS Studio",
    description: "免费开源的视频录制与直播串流软件。支持多平台，画质清晰，资源占用少，被全球数百万创作者用于录课、直播、会议存档等。",
    url: "https://obsproject.com/zh-cn/download",
    icon: "📹",
    tags: ["录屏", "直播", "视频制作"],
    stats: {
      views: 0,
      likes: 0
    }
  },
  {
    id: "376",
    name: "KDE Connect",
    description: "实现手机与电脑无缝协同的开源工具。支持共享剪贴板、跨设备文件互传、用手机当电脑遥控器/触摸板、同步手机通知，数据本地传输。",
    url: "https://apps.kde.org/zh-cn/kdeconnect/",
    icon: "🔗",
    tags: ["效率工具", "跨设备", "文件传输"],
    stats: {
      views: 0,
      likes: 0
    }
  },
  {
    id: "377",
    name: "FireAlpaca",
    description: "免费、轻量级的数字绘画软件，兼容Mac和Windows。特别适合快速制作GIF等短动画，提供丰富笔刷，软件体积小巧。",
    url: "https://firealpaca.com/",
    icon: "🦙",
    tags: ["绘画", "动画", "GIF制作"],
    stats: {
      views: 0,
      likes: 0
    }
  },
  {
    id: "378",
    name: "VLC media player",
    description: "自由、开源的跨平台多媒体播放器。可播放绝大多数音视频格式、光盘、设备及流媒体，无需额外编解码器。无广告、无跟踪。",
    url: "https://www.videolan.org/vlc/",
    icon: "▶️",
    tags: ["媒体播放", "万能播放器", "开源"],
    stats: {
      views: 0,
      likes: 0
    }
  },
  {
    id: "379",
    name: "ScreenToGif",
    description: "开源免费的屏幕、摄像头和画板录制工具，专精于GIF制作。可录制屏幕任意区域及绘画过程，并具备集成编辑器，适合制作教程。",
    url: "https://www.screentogif.com/",
    icon: "🔄",
    tags: ["GIF录制", "屏幕录制", "教程制作"],
    stats: {
      views: 0,
      likes: 0
    }
  },
  {
    id: "380",
    name: "File Converter",
    description: "简单易用的免费开源文件格式转换工具。最大特色是集成到系统右键菜单，支持视频、音频、图片、文档的批量一键转换与压缩。提供电脑端(Windows)和手机端(Android)。",
    url: "https://file-converter.org/",
    icon: "📁",
    tags: ["格式转换", "批量处理", "效率工具"],
    stats: {
      views: 0,
      likes: 0
    }
  },
];

// 获取所有唯一标签
export const getAllTags = (): string[] => {
  const tags = new Set<string>();
  NAV_DATA.forEach((item) => {
    item.tags.forEach((tag) => tags.add(tag));
  });
  return Array.from(tags).sort();
};

// 按浏览量排序
export const getSortedNavData = (data: NavItem[] = NAV_DATA): NavItem[] => {
  return [...data].sort((a, b) => {
    const viewsA = a.stats?.views || 0;
    const viewsB = b.stats?.views || 0;
    return viewsB - viewsA; // 降序排列
  });
};